### ISSUE TITLE
setmqenv

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#10]
Hi
My MQ client and ibmmq are on a Linux CentOS machine. My MQ server is running on another machine (mainframe z/OS). On the MQ server, there is a Queue Manager, M06T and two queues Q1 and Q2 (one for each direction).

Before running the samples, I run this on the client machine (taken from the readme file):
. /opt/mqm/bin/setmqenv -m M06T -k

However this fails. I get:
AMQ7048: The queue manager name is either not valid or not known.

which makes sense to me, because the client machine does not have a queue manager. It's on the server machine.

So really, I don't understand the setmqenv command above. 

Thanks for any help.
Morten

**Comment by fjbsaper** [comment]
Sourcing the setmqenv command, sets up your environment in such a way that allows this particular instance of mq to handle your calls. Your choice of the command is unfortunate as the -m flag is really reserved for a server installation, setting the environment for the installation runing the qmgr.

For the client, I suggest you use the -s flag...
