### ISSUE TITLE
Cannot install on node 12

### ISSUE THREAD

**Issue by brendon-flanagan** [ibm-messaging/mq-mqi-nodejs#101]
Get this final error on npm install

gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by ibmmqmet** [comment]
Where's the rest of the error report? And useful information such as which platform you're running on.

**Comment by brendon-flanagan** [comment]
This should be enough for you

npm install ibmmq

> ref-napi@2.1.2 install /ibmmq-demo/node_modules/ref-napi
> node-gyp-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:171:21)
gyp ERR! stack     at Request.emit (events.js:314:20)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:314:20)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:428:9)
gyp ERR! stack     at TLSSocket.emit (events.js:314:20)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:92:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Linux 3.10.0-1127.13.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /ibmmq-demo/node_modules/ref-napi
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN ibmmq-demo@1.0.0 No description
npm WARN ibmmq-demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref-napi@2.1.2 install: `node-gyp-build`
npm ERR! Exit status 1

**Comment by brendon-flanagan** [comment]
node --version
v12.19.0
