### ISSUE TITLE
How to handle auto-reconnect

### ISSUE THREAD

**Issue by creasman** [ibm-messaging/mq-mqi-nodejs#102]
I'm using version 0.9.14 of this package and am trying to set up the connection to auto-reconnect.  So far I've only set the MQCNO_RECONNECT_Q_MG flag on the connection options, like this:

```
// Set up the MQ connection object for Publisher
let cno = new mq.MQCNO();
cno.Options |= MQC.MQCNO_CLIENT_BINDING
            | MQC.MQCNO_RECONNECT_Q_MGR;

```

If I stop and start the MQ server to disrupt the connection the client does not reconnect.  I must be missing some steps. 
 Would you provide a sample of how to set up a connection with reconnect enabled?  

Thanks,
Jim

**Comment by ibmmqmet** [comment]
That ought to be enough for reconnect to work, provided the channel definitions don't disable it. In particular if SHRCONV=0, it will not reconnect.

**Comment by creasman** [comment]
I'm having trouble finding documentation on that parameter.  I don't explicitly set a value so I'm sure it must be using the default.  First question I have is should I be looking for SHRCONV or SHARECNV?  I see both referenced, but mostly the latter.  The documentation indicates the default for SHARECNV is 10 (https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q085580_.htm).  Are these parameters referring to the same thing?

Assuming SHARECNV, should I set this value explicitly to 1 in order for the reconnect to work?  If the default is 10, seems that would work.  

Thanks

**Comment by ibmmqmet** [comment]
Sorry - yes it's SHARECNV. And you can check that it is taking effect by looking at the channel and connection status via runmqsc. Something like
```
DIS CONN(*) where (appltag eq 'node') CONNOPTS
   CONNOPTS(MQCNO_HANDLE_SHARE_BLOCK, MQCNO_SHARED_BINDING, MQCNO_RECONNECT)
DIS CHS(SYSTEM.DEF.SVRCONN) CURSHCNV
  STATUS(RUNNING) CURSHCNV(1)
```

While trying this myself, I remembered that the qmgr does have to be ended appropriately. The *-r* flag is needed. That seemed to drive the reconnect successfully.
```
  endmqm -r QM1
```

**Comment by creasman** [comment]
Thanks, Mark.  I'll give this another try using `endmqm -r QM1`.  My original thought in enabling this was to make the connection resilient in the case the server takes a hard stop as well as an easy take down, and then is restarted.  We deploy MQ in a Kubernetes pod.  To recycle the server we kill the pod and let Kubernetes restart.  My goal is to not have to also restart the clients in this scenario.  

Is there a auto-reconnect scenario where the client retries every few seconds following a failure?  The mqlight and rhea AMQP clients seem to have this behavior.  

Jim

**Comment by ibmmqmet** [comment]
If the qmgr just disappears, then the client WILL try to reconnect. It actually does it at gradually increasing intervals for up to about 30 minutes. So that should be what you want to see.

But a clean shutdown of the qmgr is different - the default behaviour will disconnect the client cleanly so it won't go into retry. That's why the `-r` flag is needed as it tells the client that this should be treated similarly to a failure.

**Comment by creasman** [comment]
I have this working now.  It required changes on both the server and client sides.  Documenting here in case anyone else runs across this issue.

On the server side I had to add SHARECNV(1) to the channel definition statement.  Even though the [documentation](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q085570_.html) shows the default value is 10, it wasn't working until I set it to 1.  I haven't tried any other value.

On the client I first added MQCNO_RECONNECT to the connection options, but then started seeing an error on the publish of a message:
`MQError: PUT: MQCC = MQCC_FAILED [2] MQRC = MQRC_RECONNECT_INCOMPATIBLE [2547]`

The fix was to remove the MQPMO_WARN_IF_NO_SUBS_MATCHED setting from the MPUT options.  This apparently presumes logical ordering and is incompatible with auto-reconnect.  Fortunately, in our use case message ordering is not important.

I'm good to close this issue.  Thanks for your help.  Just have a couple more questions:

1. You mentioned the client retries in gradually increasing intervals for up to 30 minutes.  Is this configurable?  Either the interval or final timeout value?

2. Is there a way to code a notification callback in the event the 30 minutes has expired?

Jim

**Comment by ibmmqmet** [comment]
The total timeout value is configurable via the mqclient.ini file. See the MQReconnectTimeout attribute at https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.con.doc/q016860_.htm

In many environments, you can get a callback when the timeout expires via the MQCB verb. But that is not available through this particular interface because of how Node's threading model doesn't play well with the underlying locking - it leads to deadlocks.
