### ISSUE TITLE
Having issue with user authorisation error - MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035]

### ISSUE THREAD

**Issue by brendon-flanagan** [ibm-messaging/mq-mqi-nodejs#105]
Not sure what I've not done right, but I've created the mq.MQCSP() object, set the csp.UserId and assigned to the cmo.SecurityParms object.

I know this is working on the mq connect as I can see that on the MQ side of the fence and can also deliberately cause a failure with wrong userid.

However, when I try and then open a queue, I get the mqrc 2035 error, and I see on the MQ side of the system user id that I am running node under being used instead, vs where I need to be able to set this explicitly, ie not go simply adding individual authority records to every single queue in MQ

**Comment by ibmmqmet** [comment]
I'm not really certain what you are saying. But you DO need to be authorised for any resources that you want to use such as queues. Those authorisations can be granted via wildcards though. See the documentation for the [setmqaut command](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.ref.adm.doc/q083500_.htm) The queue manager error log will show authorisation errors and tell you what permissions you are missing.

**Comment by brendon-flanagan** [comment]
No, that’s not the problem I don’t think, as I have a java app on same machine as the nodejs app, which has no problem.   In that, I’m setting the AlternateUserId, when doing the same in Node, it doesn’t like it at all, ie that actually crashes the .open function.   Yet to debug further into it to see why.

**Comment by Kannndev** [comment]
I do have the same issue. Any updates on this. Whenever I try to connect to remote MQ it's taking my system's user id where the program is running instead of what I set in the MQCSP object.

**Comment by freerider7777** [comment]
Same thing... Seems line setting UserId and Password does not work:

var csp = new mq.MQCSP();
csp.UserId = ".\user";
csp.Password = "...";
// Make the MQCNO refer to the MQCSP
// Uncomment next line to use the userid/password
cno.SecurityParms = csp;

**Comment by freerider7777** [comment]
Any updates on this? We have to run the app "under the user", cannot set the user in code...

**Comment by ibmmqmet** [comment]
You have given no real information such as error log contents, or configuration details. There is plenty of information available that you should be able to search for on how to resolve authentication or authorisation errors.

**Comment by AndreMHer** [comment]
Hi I'm fascing a similar error on this, I know that the user that is running the application, does not exists in the MQ server side, therefore I'm trying to send the user that's exists in the MQ Server via code. However i see in the MQ server logs the user that's reaching the mq server is still the same. Not changing to the proper user. I attach the line of code where I'm setting the user

const mqUser = process.env.GARS_MQ_USER;
  const mqPwd = process.env.GARS_MQ_PASSWORD;
  const mqSenderChannel = process.env.GARS_SENDER_MQ_CHANNEL;
  const mqSenderQM = process.env.GARS_SENDER_QM;
  const mqSenderQueue = process.env.GARS_SENDER_QUEUE;
  const mqSenderHost = process.env.GARS_SENDER_MQ_HOST;
  const mqSSLClientAuth = process.env.GARS_SSL_CLIENT_AUTH;
  const mqSSLCipherSpec = process.env.GARS_SSL_CIPHER_SPEC;
  const mqSSLKeyRepository = process.env.GARS_SSL_KEY_REPOSITORY;
  const mqClientConn: mq.MQCD = new mq.MQCD();
  const mqSecurityParams: mq.MQCSP = new mq.MQCSP();
  const mqConnectionOptions: mq.MQCNO = new mq.MQCNO();
  const queue = new mq.MQOD();
  const mqSSLConfig = new mq.MQSCO();
  
 mqSecurityParams.UserId = mqUser;

I'm setting my env variable to 'mqUser'
However the error i see in the server side is:

AMQ9557E: Queue Manager User ID initialization failed for '07776c781' 

User 077... is the user in my client executing the node code, it is not taking the User i specified in the env variables, which I'm assigning to the security Params. 

My QM Manager does not have the MQ_Required Authorization. Therfore i do not need to send a password.

**Comment by chughts** [comment]
@AndreMHer Are you running on Windows ?

**Comment by AndreMHer** [comment]
Yes running in.windows on the client side.

**Comment by ibmmqmet** [comment]
You cannot simply assert an identity from the client. If you send a userid in the CSP structure, then it needs to be accompanied by a password unless the system allows authentication to happen without a password (that can be done with custom PAM configurations on Unix but would not be common practice). 

The CHCKLOCL/CHCKCLNT configurations on the queue manager determine whether the authentication step is done at all, but 'NONE' means that no account is taken at all of the CSP contents.

If you simply want to adopt a userid and not care about authentication then use CHLAUTH mapping rules (preferred) or explicitly set the MCAUSER on your svrconn channel.
