### ISSUE TITLE
MQSCA_NEVER_REQUIRED does not work

### ISSUE THREAD

**Issue by vitalif** [ibm-messaging/mq-mqi-nodejs#109]
Hi

I'm trying to connect to a TLS-enabled IBM MQ using mq-mqi-nodejs 0.9.16 **without** client authentication. Like the following:

```js
const ibmmq = require('ibmmq');

async function test_mq()
{
    const opt = new ibmmq.MQCNO();
    opt.ClientConn = new ibmmq.MQCD();
    opt.ClientConn.ConnectionName = "t5mql(1413)";
    opt.ClientConn.ChannelName = "DEV.SRVCONN";
    opt.ClientConn.SSLCipherSpec = "ANY";
    opt.ClientConn.SSLClientAuth = ibmmq.MQC.MQSCA_NEVER_REQUIRED;
    opt.SecurityParms = new ibmmq.MQCSP();
    opt.SecurityParms.UserId = 'admin';
    opt.SecurityParms.Password = '1';
    const conn = await ibmmq.ConnxPromise('MQDEV', opt);
}

test_mq().catch(console.error);
```

I get:

```
MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CD_ERROR [2277]
    at .../node_modules/ibmmq/lib/mqi.js:776:17
    at Object.<anonymous> (.../node_modules/ffi-napi/lib/_foreign_function.js:115:9) {
  name: 'MQError',
  message: 'CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CD_ERROR [2277]',
  mqcc: 2,
  mqccstr: 'MQCC_FAILED',
  mqrc: 2277,
  mqrcstr: 'MQRC_CD_ERROR',
  version: '0.9.16',
  verb: 'CONNX'
}
```

The log `~/IBM/MQ/data/errors/AMQERR01.LOG` contains the following:

```
AMQ9498E: The MQCD structure supplied was not valid.

EXPLANATION:
The value of the 'SSLClientAuth' field has the value '2'. This value is invalid
for the operation requested.
ACTION:
Change the parameter and retry the operation.
----- amqrcdua.c : 390 --------------------------------------------------------
```

If I don't set MQSCA_NEVER_REQUIRED then it requires the client certificate and gives MQRC_KEY_REPOSITORY_ERROR.

So. MQSCA_NEVER_REQUIRED seems to not work.

**Comment by ibmmqmet** [comment]
MQSCA_NEVER_REQUIRED is only valid for MQTT channels defined in the queue manager. So the error message is correctly telling you the problem.

If you don't want to use client-side certificates then you should use MQSCA_OPTIONAL, and have that matching value on the SVRCONN definition too. OPTIONAL gives you the choice of whether or not to present a certificate from the client. 

When using TLS you still always need a keystore (kdb) that at minimum contains the signing or public certs to validate the certificate sent from the qmgr. There's no both-sides certificate-free option for client connectivity.

**Comment by vitalif** [comment]
But it works in Java...

**Comment by vitalif** [comment]
I mean, Java connectivity with the exact same server works without any key repositories

**Comment by vitalif** [comment]
It works in Java by mocking the trust checks, but it works :-)

It's a strangle implementation anyway. It should at least use the system key store instead of its own cryptic format

**Comment by ibmmqmet** [comment]
Java != JavaScript of course ... 

JREs often include a default truststore with common signer certs or refer to a system-wide JKS truststore when none is explicitly specified. I don't know that I actually like that behaviour because it could allow bad qmgrs to be considered trusted by default.

The keystore used by all the languages that are built on the MQ C client is the kdb format. That's the same format as used by the qmgr (and various other products too). It combines both the personal keystore and truststore that are separated in the Java case. There's lots of docs on how to work with it in the MQ KnowledgeCentre.

**Comment by ibmmqmet** [comment]
closing as answered
