### ISSUE TITLE
Getting MQRC_HOST_NOT_AVAILABLE when using Node.js with mTLS 

### ISSUE THREAD

**Issue by shoebvb** [ibm-messaging/mq-mqi-nodejs#110]
We are trying to connect to MQ server (version 9.x, client version 9.2.0.0-IBM-MQ-Toolkit-MacX64) with mTLS auth and observed that connection is failing with MQRC_HOST_NOT_AVAILABLE.

More details about node js client: basicput.js
https://github.com/ibm-messaging/mq-dev-patterns/tree/master/Node.js

Observation:

Java Based MQ Client - working
IBM MQ Client - not working
Node JS MQ Client - not working
MQ Explorer - working

Java based MQ client and MQ Explorer are working fine, however Node JS Client and native MQ client is not working.

In both case we are getting MQRC_HOST_NOT_AVAILABLE error
basicput.js results into following failure. Server is up and we can connect to it using MQ Explorer.

```
 DEBUG=amqs*:* node basicput.js
[ibmmq] 2021-01-22T18:13:34.120Z  : Tuning Parameters are now {"maxConsecutiveGets":100,"getLoopPollTimeMs":10000,"getLoopDelayTimeMs":250,"syncMQICompat":false,"debugLongCalls":false,"debugLog":true}
  amqsput:info Running on  darwin +0ms
  amqsput:info Starting up Application +0ms
  amqsput:info CCDT URL export is not set, will be using json environment client connections settings +0ms
  amqsput:info Connections string is  beta2-dev-1-mq.oms.supply-chain.ibm.com(15443) +1ms
  amqsput:info Will be running in TLS Mode +0ms
  amqsput:info Key Repository has been specified +0ms
  amqsput:info Attempting Connection to MQ Server +0ms
  amqsput:info Application Start Completed +17ms
  amqsput:info Inside Connection Callback function +471ms
  amqsput:warn Error Detected making Connection MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_HOST_NOT_AVAILABLE [2538]
    at /Users/svbihari/Downloads/mq-dev-patterns-master/Node.js/node_modules/ibmmq/lib/mqi.js:776:17
    at Object.<anonymous> (/Users/svbihari/Downloads/mq-dev-patterns-master/Node.js/node_modules/ffi-napi/lib/_foreign_function.js:115:9) {
  mqcc: 2,
  mqccstr: 'MQCC_FAILED',
  mqrc: 2538,
  mqrcstr: 'MQRC_HOST_NOT_AVAILABLE',
  version: '0.9.16',
  verb: 'CONNX'
} +0ms
```

 
**Connection to server seems to be fine.**

 nc -v beta2-dev-1-mq.oms.supply-chain.ibm.com 15443
Connection to beta2-dev-1-mq.oms.supply-chain.ibm.com port 15443 [tcp/*] succeeded!

**Key db setup:**

runmqckm -keydb -create -db key.kdb -pw password -type cms -stash
runmqakm -cert -import -db ../mqjc/certs/beta2cert.p12 -pw password -type pkcs12 -target key.kdb -target_pw password -target_type cms
runmqakm -cert -list -db key.kdb -stashed

Certificates found
* default, - personal, ! trusted, # secret key
!   DigiCert
-   owner=sheobvb-mq,platform=mqexplorer

Debugging further with Wireshark we noticed that SNI as part of header wasn't sent correctly.

See below screenshot:

 
![Snip20210127_3](https://user-images.githubusercontent.com/78171815/106185282-9e992480-6170-11eb-9fda-2f1371e4706f.png)
![Snip20210127_4](https://user-images.githubusercontent.com/78171815/106185294-a35dd880-6170-11eb-99dd-16b12e7cb43c.png)

SNI server name is coming out as system2e-tls2e-svrconn.chl.mq.ibm.com, whereas Java client and MQ explore server name is coming out correctly beta2-dev-1-mq.oms.supply-chain.ibm.com.

Here is the screenshot for MQ Explorer Communication.

![Snip20210127_5](https://user-images.githubusercontent.com/78171815/106185344-b4a6e500-6170-11eb-8fab-73f6ef8bc35b.png)

Looking for the help to understand how we can override the SNI sent by node js to match what Java client and MQ explorer is sending.

Issue is at the C TLS layer in the underlying MQI library, as such I'm raising the issue here.

**Comment by ibmmqmet** [comment]
You can control how SNI is used in clients built on the C implementation. Read the documenation in [the KC](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.con.doc/q019040_.html)

**Comment by dware30** [comment]
As Mark says, the contents of the SNI header can be controlled through configuration. In this case, you'll want to change the OutboundSNI setting of the [client side configuration](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.con.doc/q016900_.htm) rather than the queue manager side.

The reason for the choice here is that the SNI contents is used for routing traffic and different routing layers want different things to be in there. For example [OpenShift requires the hostname](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.ctr.doc/cc_conn_qm_openshift.htm), as you seem to be needing.

**Comment by shoebvb** [comment]
OutboundSNI did the trick. Thank you so much. 


Key DB setup:

```
runmqakm -keydb -create -db key.kdb -pw ***** -type cms -expire 365 -stash
runmqakm -cert -add -db key.kdb -label ibmwebspheremq_om_qmgr -file DigiCertHighAssuranceEVRootCA.crt.pem -pw ******
runmqakm -cert -import -file owner=sheobvb-mq,platform=mqexplorer.p12 -type pkcs12 -pw ****** -target key.kdb -target_pw passw0rd

```

mqclient.ini

```
SSL: 
        OutboundSNI=HOSTNAME
        AllowOutboundSNI=YES

```

Node js code change:

```
cd.SSLClientAuth = MQC.MQSCA_REQUIRED;
sco.CertificateLabel = "owner=sheobvb-mq,platform=mqexplorer";
```


Result:

... Node.js % DEBUG=amqs*:* node basicput.js
```
[ibmmq] 2021-01-29T16:50:25.511Z  : Tuning Parameters are now {"maxConsecutiveGets":100,"getLoopPollTimeMs":10000,"getLoopDelayTimeMs":250,"syncMQICompat":false,"debugLongCalls":false,"debugLog":true} 
  amqsput:info Running on  darwin +0ms
  amqsput:info Starting up Application +0ms
  amqsput:info CCDT URL export is not set, will be using json envrionment client connections settings +0ms
  amqsput:info Connections string is  beta2-dev-1-mq.oms.supply-chain.ibm.com(15443) +1ms
  amqsput:info Will be running in TLS Mode +0ms
  amqsput:info Key Repository has been specified +0ms
  amqsput:info Attempting Connection to MQ Server +0ms
  amqsput:info Application Start Completed +14ms
  amqsput:info Inside Connection Callback function +581ms
  amqsput:info MQCONN to OM_QMGR successful  +0ms
  amqsput:info Inside MQ Open Callback function +67ms
  amqsput:info MQOPEN of SHOEBVB_Q successful +0ms
  amqsput:info MsgId:  414d51204f4d5f514d4752202020202096ec1260eff42f22 +73ms
  amqsput:info MQPUT successful +0ms
  amqsput:info MQCLOSE successful +49ms
  amqsput:info MQDISC successful +50ms
```
