### ISSUE TITLE
Backout Msg not moving to Backout Queue

### ISSUE THREAD

**Issue by prabhatmishra33** [ibm-messaging/mq-mqi-nodejs#111]
using version 0.9.16

Dear Team,
My understanding is when the BackoutCount >= Backout Threshold, the Msg should move to the backout queue automatically. but this is not the case with this library the message keeps coming.

Could you please help me here?

**Comment by ibmmqmet** [comment]
Automatic movement to a backout queue is only handled by the JMS interface. As this package is based on the C client you need to manage it yourself. See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.ref.adm.doc/q085690_.html#q085690___boqname

> BOQNAME (queue-name): Use this parameter to set or change the back out queue name attribute of a local or model queue. **Apart from allowing its value to be queried, the queue manager does nothing based on the value of this attribute.** IBM MQ classes for JMS transfers a message that is backed out the maximum number of times to this queue.

**Comment by prabhatmishra33** [comment]
Thanks for the quick reply.
