### ISSUE TITLE
Can't read MQC.MQEVENT type MQMD headers

### ISSUE THREAD

**Issue by RayMN** [ibm-messaging/mq-mqi-nodejs#124]
System Information:
- Nodejs is on Ubuntu 20.04
- MQ9.2.2 is on CentOS v8
- mq-mqi-nodejs version downloaded latest and installed 05/30/2021

I am trying to get to the MQEVENT type messages and I'm getting errors.

[amqsget.zip](https://github.com/ibm-messaging/mq-mqi-nodejs/files/6585372/amqsget.zip)

I have attached my modified version of your amqsget.js sample that includes my QMGR/QUEUE config (which works and I can read "normal" messages). But when I try to read MQEVENT type messages it seems to ignore the MQC.MQEVENT MQMD header type in the case statement on line 86. So I added a simple console.log at line 83 to print out the value of MQC.MQEVENT and I get this error ...

```
Sample AMQSGET.JS start
MQCONN to C8QM successful 
MQOPEN of SYSTEM.ADMIN.CHANNEL.EVENT successful
MQMD Format is -MQEVENT-
terminate called after throwing an instance of 'Napi::Error'
  what():  Cannot read property 'toString' of undefined
Aborted (core dumped)
```
This my be due to my lack of knowledge about MQMD headers but if you run the sample the log statement on line 81 does report the MQMD format as MQEVENT, the case statement just ignores it later because I don't think it's defined ... or I'm not using it right.

Thanks,
Ray

**Comment by ibmmqmet** [comment]
a) (minor) the constant that should be used is MQC.MQFMT_EVENT, not MQC.MQEVENT as in your code
b) (major) there is no inbuilt support in this package for working with PCF structures including the MQCFH. So calling non-existent methods on non-existing structures ` mq.MQCFH.getHeader(buf)` is not going to work

While a CFH parser and builder could be done on similar lines to the DLH parser, it's not something I've got any immediate plans for. Handling PCF is not just a matter of doing the CFH structure, but all the associated pieces like MQCFST for the different element types.

**Comment by RayMN** [comment]
Hi Mark,
I figured out A and hence B after a bit more digging and a few beverages with friends last evening.
I will find a different way to get at the messages. We are using MQ Appliances and I need a way to collect audit and control events from the QMGRs to put into an external log. I was planning to take this and build Node-RED nodes from them. I may still (with permission) because I can get at "normal" MQ messages, but the priority of it has went from work to hobby.
