### ISSUE TITLE
install does not delete downloaded mq client redist archive file

### ISSUE THREAD

**Issue by tbglazer** [ibm-messaging/mq-mqi-nodejs#127]
Please include the following information in your ticket.

- mq-mqi-nodejs version(s) that are affected by this issue.
- A small code sample that demonstrates the issue.

**Comment by tbglazer** [comment]
Changing in postinstall.js/cleanup() from unlink to unlinkSync make it work.

**Comment by ibmmqmet** [comment]
Thanks for the report. I'd have expected that once the unlink starts, it's going to finish, as it's such a simple system call - even if the calling script ends. It's always worked for me. But perhaps different speed machines or filesystems behave differently. So I'll patch that for the next update.

**Comment by ibmmqmet** [comment]
included in 0.9.18
