### ISSUE TITLE
Cannot find MQ C library

### ISSUE THREAD

**Issue by Dkbharti** [ibm-messaging/mq-mqi-nodejs#128]
I simply installed 'ibmmq' package using "npm i ibmmq" and tried to run amqsconn.js from samples. But I'm getting this below error:

Cannot find MQ C library.
  Has the C client been installed?
  Have you run setmqenv?

**Comment by ibmmqmet** [comment]
You don't say which platform you're running on.

**Comment by Dkbharti** [comment]
Hi ,
I was working on windows.
My issue has been resolved.
