### ISSUE TITLE
Threading model without polling?

### ISSUE THREAD

**Issue by freerider7777** [ibm-messaging/mq-mqi-nodejs#129]
Hi!
Is there a possibility of changing the threading model like written here?
https://nodeaddons.com/c-processing-from-node-js-part-4-asynchronous-addons/

"polling" takes resources, if you need quick reaction the polling interval is small, which takes cpu on the client and on the MQ...

**Comment by ibmmqmet** [comment]
I've got no current plans to do that, though it's always been on my list of low-priority tasks if I ever get round to it. It's a major rewrite and complex. And it might not actually work anyway, given the conflicts that have already been seen between Node and the MQ threading rules.

**Comment by freerider7777** [comment]
That's complex for sure! :))
Thanks for your efforts with this library.
