### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#13]
Hi
Maybe a stupid question. Is buffer sizes (for the messages) something I need to worry about, or is it all hidden for me by ibmmq? If not, where do I configure this?

Thanks for any help.
Morten

**Comment by ibmmqmet** [comment]
You don't need to create buffers to receive messages. The MQ code handles all that. But you may need to copy received messages after they have been delivered to a callback function, as the underlying buffer may be reused for a subsequent message.
