### ISSUE TITLE
Got MQRC_CHANNEL_CONFIG_ERROR [2539]

### ISSUE THREAD

**Issue by zkxil** [ibm-messaging/mq-mqi-nodejs#131]
ibmmq: 0.9.18
```
var qMgr = "xxxx";
var cno = new mq.MQCNO();
cno.Options = MQC.MQCNO_CLIENT_BINDING;

var cd = new mq.MQCD();
cd.ConnectionName = "xxxxxxxx.ahe.boulder.ibm.com(1414)";
cd.ChannelName = "xxx.MQE.SVRCONN";
// Make the MQCNO refer to the MQCD
cno.ClientConn = cd;

mq.ConnxPromise(qMgr, cno)
    .then(hConn => {
        console.log("MQCONN to %s successful ", qMgr);
```

I got error message below
```
MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]
```
Can you give me some suggestion about this error?

**Comment by zkxil** [comment]
> 2539 (09EB) (RC2539): MQRC_CHANNEL_CONFIG_ERROR
 Explanation
 An MQCONN call was issued from a client to connect to a queue manager but the attempt to establish communication failed. Common causes of this reason code are:
 The server and client cannot agree on the channel attributes to use.
 There are errors in one or both of the QM.INI or MQCLIENT.INI configuration files.
 **The server machine does not support the code page used by the client.**

Thanks for reply.
I searched in Google, thought the three point should be the reason lead to error.
Is there any document about ibmmq lib version mapping to IBM MQ server, or I need to change some configurations to adapt the NodeJS client?

**Comment by ibmmqmet** [comment]
Also in the documentation is this:
> Programmer response: Examine the queue manager and client error logs for messages explaining the cause of the problem.

What did the errror logs say?

**Comment by zkxil** [comment]
It should be something wrong with my local env, will close this issue.
