### ISSUE TITLE
MQRC_DATA_LENGTH_ERROR when Put message

### ISSUE THREAD

**Issue by mariojunior** [ibm-messaging/mq-mqi-nodejs#133]
Hi!
I'm working on a very busy messaging system, for 99% messages we're able to consume, processing and send to other queues, really good! 

However, for 1% we're dealing with very long size message, although I'm able to consume them, after some processing (and appending more info into) I'm getting this issue when I'm going to publish the message in another queue: 
{"name":"MQError","message":"PUT: MQCC = MQCC_FAILED [2] MQRC = MQRC_DATA_LENGTH_ERROR [2010]","mqcc":2,"mqccstr":"MQCC_FAILED","mqrc":2010,"mqrcstr":"MQRC_DATA_LENGTH_ERROR","version":"0.9.14","verb":"PUT"}

I'm checking the source code and I couldn't find a way to set the MAXMSGL property, which could be a solution according to the IBM's documentation:
https://www.ibm.com/docs/en/ibm-mq/9.0?topic=codes-2010-07da-rc2010-mqrc-data-length-error

Is there any way to set it ?

- mq-mqi-nodejs version being used: 0.9.15

Thanks.

**Comment by ibmmqmet** [comment]
You don't say what "very long" means so it's not possible to guess what default limit you're reaching. 

MAXMSGL is set by the administrator on the channel, the queue and the queue manager. See, for example, https://www.ibm.com/docs/en/ibm-mq/9.2?topic=reference-alter-channel-alter-channel-settings

Client channels CAN specify a value in the MQCD structure that may be passed to MQCONNX, but that will only cause negotiation of the lower value compared to the other end of the channel.

**Comment by mariojunior** [comment]
Thanks, Mark.
Unfortunately I didn't catch the message which caused the issue, I'll try to run another stress test (which generates random messages' content). It's an error never seen with the Java client before but I'll spend more time investigating it.

I'm going to close this issue.
Thanks for the clarification about settings.

**Comment by mariojunior** [comment]
Just giving a final update:
I was getting this issue when my nodejs app tried to published an enriched message which sized over than 4MB and the queue limit was set to 4MB in the broker's side.
So, after changing the "Maximum message length (bytes)" set to 10MB (yep, I'm really playing with large messages), it was solved.

![image](https://user-images.githubusercontent.com/444465/152455003-f593d9e9-2d8c-4de8-ba67-83da3e66ecc6.png)


Thanks.
