### ISSUE TITLE
long npm install without information what is going on

### ISSUE THREAD

**Issue by freerider7777** [ibm-messaging/mq-mqi-nodejs#136]
windows 11, node.js 16.13.1
when doing npm install it "hangs" in such state (I suppose downloading IBMMQ redist libraries) but it's not obvious what's going on:

![image](https://user-images.githubusercontent.com/6572573/147066099-ae6f98e7-5b59-4bcf-bcb8-8713fc147e9e.png)

after several minutes all is ok:
![image](https://user-images.githubusercontent.com/6572573/147066376-f54a8b53-4e39-45d4-aba9-5d0246afcb1b.png)

It's strange, but on windows 10, node 14.18.1 I see the message about downloading:
![image](https://user-images.githubusercontent.com/6572573/147066893-c1e540a7-e381-470f-bf3a-4958d8197031.png)

**Comment by ibmmqmet** [comment]
See, for example, https://github.com/npm/feedback/discussions/592

This appears to be a change in NPM, not something this repo has any control over. Running `npm --foreground-scripts install` does show the output, though I understand that's not the default.  You can change the default behaviour for future installs with 
`npm config set foreground-scripts=true`

**Comment by freerider7777** [comment]
Thanks for the detailed information!
