### ISSUE TITLE
Question: Is there a way to change ACK mode?

### ISSUE THREAD

**Issue by mike-feldmeier** [ibm-messaging/mq-mqi-nodejs#139]
**This is a fantastic project; thank you for putting it together**

Is there a way to specify client acknowledgement instead of auto acknowledgement?  I looked through the code and didn't see anything, but then I am far from an expert on MQ internals.

Thanks!

**Comment by ibmmqmet** [comment]
Client/Auto acknowledgement is primarily a JMS concept, or in some other messaging systems without reliable connectivity.

In the MQI, you use transactions instead to demarcate when you've sucessfully processed something. So use options like MQPMO_SYNCPOINT or MQGMO_SYNCPOINT followed by the mq.Cmit verb.

https://www.ibm.com/docs/en/ibm-mq/9.2?topic=queuing-committing-backing-out-units-work

**Comment by mike-feldmeier** [comment]
In the past I've only approached it through JMS, so this is something new to learn.  Thank you very much for your explanation!
