### ISSUE TITLE
Message is displayed with unreadable characters

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#14]
Hi
When I run amqsget.js, I get a lot of unreadable characters (see below). Any idea what my problem is?

Thanks for any help.
Morten

[morten@localhost samples]$ node amqsget.js QA.TEST07.FHS_NITRA_RESOURCE_REP M06T
Sample AMQSGET.JS start
MQCONN to M06T successful 
MQOPEN of QA.TEST07.FHS_NITRA_RESOURCE_REP successful
message <Lo���@�������~�K�@��������~���`����`�@onL���nL���n��La���nL���`��n���`����La���`��nL����`��n��La����`��nL���`��n��z��@���@�������La���`��nL��`���nL��n��z��@���@�������La��nL����n��������La����nL�`��n��z��@���@�������La�`��nL�`��n��z��@��@������@����\La�`��nL�`��n��z��@���@����La�`��nL�`��n��z���@���@����La�`��nL�`��n��z���@��@������@����\La�`��nLa��`���nLa���n>
no more messages
MQCLOSE successful
MQDISC successful

**Comment by ibmmqmet** [comment]
probably you need to set the MQGMO_CONVERT option in the GMO.Options to get EBCDIC translated to ASCII (that's the simplistic answer, but you should read up on code pages, data conversion etc).

**Comment by mortenLom** [comment]
Thanks. I will try this. :-)
Morten

**Comment by mortenLom** [comment]
Wow. It worked. Thanks :-)
