### ISSUE TITLE
Issue with docker image run

### ISSUE THREAD

**Issue by prabhatmishra33** [ibm-messaging/mq-mqi-nodejs#143]
Dear Team,

I am facing an issue in running up the docker image for my service which consumes the IBMMQ package.

PFB the related package details:

`    "node_modules/ibmmq": {
      "version": "0.9.18",
      "hasInstallScript": true,
      "license": "Apache-2.0",
      "dependencies": {
        "ffi-napi": ">=4.0.3",
        "ref-array-di": ">=1.2.2",
        "ref-napi": "^3.0.3",
        "ref-struct-di": ">=1.1.1",
        "unzipper": ">=0.10.11"
      }`

Few days before the below docker image used to work fine.

# STAGE1: BUILD
FROM node:16.13.2-bullseye-slim AS base

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

RUN echo $(ls -1 ./)
RUN echo $(ls -1 ./src)=
RUN apt-get update && apt-get install --yes curl g++ make git python3 
RUN npm install

RUN npm run app-build
COPY . .

# STAGE2: RELEASE
FROM node:16.13.2-bullseye-slim AS release

WORKDIR /app

COPY --from=base /app/build/src ./src
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package*.json ./
COPY --from=base /app/tsconfig.json ./

CMD node src/index.js

Now the above image gets built but while running the container, I always get an issue as below.

 - <container-id>: container <container-name> is backing off waiting to restart
    - <verical>-dev:pod/<verical>-<container-name>-ro-5dbc6cd9c8-x48tj: container <container-name> is backing off waiting to restart
      > [ <verical>-<container-name>-ro-5dbc6cd9c8-x48tj <container-name>] Cannot find MQ C library.
      > [ <verical>-<container-name>-ro-5dbc6cd9c8-x48tj <container-name>]   Has the C client been installed?
      > [ <verical>-<container-name>-ro-5dbc6cd9c8-x48tj <container-name>]   Have you run setmqenv?
 - <container-id> failed. Error: container <container-name> is backing off waiting to restart.

**Comment by ibmmqmet** [comment]
answered in https://stackoverflow.com/questions/72831629/issue-with-ibmmq-docker-container-run/72837197#72837197

**Comment by prabhatmishra-metro** [comment]
Purpose of this issue is served, Please close this issue.
