### ISSUE TITLE
Any way to get more debug info? MQRC_SSL_INITIALIZATION_ERROR

### ISSUE THREAD

**Issue by Fossil01** [ibm-messaging/mq-mqi-nodejs#146]
We connect to the queue of our client, so we don't have any control over the server side. Just our client.

```
[04/08/2022 10:36:11.060] [LOG]    trying to connect to queue manager XXX03 at host x.x.x.x(1414)
[04/08/2022 10:36:11.242] [ERROR]  error connecting to IBM mq: MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]
```

Our client says they see nothing in their logs and I don't see anything else than the error above. This randomly started yesterday.

Any pointers?

**Comment by ibmmqmet** [comment]
I would expect there to be a lot more information in MQ error logs (AMQERR*.LOG files) on either or both of the client and the qmgr. Most commonly, that error comes from either not being able to access the key repository or something wrong with the certificates. If it started yesterday, then the important question would be what changed on either side of the connection - new versions of something? config changes? updated certs?

**Comment by ibmmqmet** [comment]
The standard places for MQ client-side error logs will usually be under either /var/mqm/errors or $HOME/IBM/MQ/data/errors depending on how the client has been installed
