### ISSUE TITLE
Set the App Name

### ISSUE THREAD

**Issue by mariojunior** [ibm-messaging/mq-mqi-nodejs#148]
Is there any way to set the Application Name that is connected to the broker?
All my nodejs apps only show "node" and would be useful for me showing meaningful names indicating who is producing/consuming msgs to/from

![image](https://user-images.githubusercontent.com/444465/190029749-bc10d3a0-621d-4e42-a652-e06393b80189.png)

Thanks.

**Comment by ibmmqmet** [comment]
Look at the samples/amqsconn.js program which sets `cno.ApplName`. For alternative mechanisms, read the product documentation at https://www.ibm.com/docs/en/ibm-mq/9.3?topic=languages-using-application-name-in-supported-programming where the 'C' client information applies.

**Comment by mariojunior** [comment]
Cool, legend!
And I found out it's a MQT.CHAR28 and funny the WebSphere Java client uses the 28 chars 😃 
Thanks, sir!
