### ISSUE TITLE
Value to be set for setmqenv!

### ISSUE THREAD

**Issue by sikkans** [ibm-messaging/mq-mqi-nodejs#149]
Hi,

I cloned the library and ran non install after setting MQIJS_NOREDIST to '', so that it does not get downloaded. Rather I have downloaded it manually and unzipped the contents.
When I run one of the sample program, I get below error

Cannot find MQ C library.
System appears to be : win32[x64]
Has the MQ C client been installed?
Have you run setmqenv?

What value should be set to variable setmqenv?

**Comment by ibmmqmet** [comment]
setmqenv is a program - which is why you "run" it, not set it.

And it is described in the product documentation [here](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=reference-setmqenv-set-mq-environment)
