### ISSUE TITLE
TypeScript declaration problem

### ISSUE THREAD

**Issue by tomika** [ibm-messaging/mq-mqi-nodejs#152]
SubPromise method second parameter defined as 
    MQObject 
in index.d.ts:1032 but it should be defined as 
    MQObject | null 
since it can be null according to comment in index.d.ts:1020

It's in the latest version 1.0.3 also.

**Comment by ibmmqmet** [comment]
Thanks for the report. I'll fix it for the next update. Looks like `SubSync` has the same issue.

**Comment by tomika** [comment]
Maybe, I did not checked other occurences.
Thanks in advance.

**Comment by ibmmqmet** [comment]
fixed in 1.0.4
