### ISSUE TITLE
Unable to install ibmmq

### ISSUE THREAD

**Issue by eisheeta** [ibm-messaging/mq-mqi-nodejs#153]
While trying to install ibmmq package, I'm getting the following gyp error. Please assist with what could be wrong and how to go about correcting it.

Node v16.17.0
IBMMQ v1.0.3

npm ERR! code 1
npm ERR! path []/node_modules/ref-napi
npm ERR! command failed
npm ERR! command sh /tmp/install-e2117abd.sh
npm ERR! make: Entering directory `[]/node_modules/ref-napi/build'
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/../node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   CXX(target) Release/obj.target/binding/src/binding.o
npm ERR! make: Leaving directory `[]/node_modules/ref-napi/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.14 found at "[]/tools/Python3.7/bin/python3"
npm ERR! gyp info spawn []/Python3.7/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '[]tools/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '[]/node_modules/ref-napi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '[]tools/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '[]tools/headerV16_17_0/node-v16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=[]/tools/headerV16_17_0/node-v16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=[]/tools/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=[]/tools/headerV16_17_0/node-v16.17.0/$(Configuration)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=[]/node_modules/ref-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++14’
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit ([]/tools/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.76.1.el7.x86_64
npm ERR! gyp ERR! command "[]/tools/node-v16.17.0-linux-x64/bin/node" "[]tools/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /[]/node_modules/ref-napi
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
.

**Comment by ibmmqmet** [comment]
The line `g++: error: unrecognized command line option ‘-std=gnu++14’ might help. It suggests that you might have an old or unexpected C++ compiler perhaps? 

https://stackoverflow.com/questions/70681713/g-error-unrecognized-command-line-option-std-gnu14-with-gcc-version-9 might point towards a solution
