### ISSUE TITLE
ConnxSync is not a function error

### ISSUE THREAD

**Issue by ImaBadSlime** [ibm-messaging/mq-mqi-nodejs#160]
mqi.js

exports.fOpen = function (jsqMgrName, jsCno, cb) {
  log.traceEntry('ConnxSync');
  checkParamCB(cb);
  connx(jsqMgrName,jsCno,false,cb);
  log.traceExit('ConnxSync');
};

should be 

exports.ConnxSync = function (jsqMgrName, jsCno, cb) {
  log.traceEntry('ConnxSync');
  checkParamCB(cb);
  connx(jsqMgrName,jsCno,false,cb);
  log.traceExit('ConnxSync');
};

This typo is a source of problem
fix pls =)

**Comment by ibmmqmet** [comment]
I don't see any typo in the current committed tree.

**Comment by ImaBadSlime** [comment]
True
that was my bad, sorry
