### ISSUE TITLE
Facing issue while setting up MQ Redist Client package on API running on Node js 18 version

### ISSUE THREAD

**Issue by Ajmalshaikh89** [ibm-messaging/mq-mqi-nodejs#166]
Please include the following information in your ticket.
- mq-mqi-nodejs version(s) that are affected by this issue: Node Version 18.8.0
-Hi Team,
we are setting up MQ container on our api pods which run on the above Node JS version. When we are running the dockerfile, we are getting the below issue:
Cannot find MQ C library.
System appears to be: linux[x64]
  Has the MQ C client been installed?
  Have you run setmqenv?
/opt/app/node_modules/ibmmq/lib/mqi.js:450
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/opt/mqm/lib/libmqm_r.so'
    at Object.openSync (node:fs:599:3)
    at readFileSync (node:fs:467:35)
    at new DynamicLibrary (/opt/app/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
    at Object.Library (/opt/app/node_modules/ffi-napi/lib/library.js:47:10)
    at loadLib (/opt/app/node_modules/ibmmq/lib/mqi.js:303:18)
    at loadLibMulti (/opt/app/node_modules/ibmmq/lib/mqi.js:434:13)
    at Object.<anonymous> (/opt/app/node_modules/ibmmq/lib/mqi.js:455:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/opt/mqm/lib/libmqm_r.so'
}

Node.js v18.8.0
Can you assist in letting us know why are getting this. We are running our containers on Debian 10 version. We have already done this setup on another api, but we did not get this error. Seems like Postinstall script at npm install stage is trying to run a script which is not able to complete the MQ Client C location. When we run this in local dev environment, it works fine. Can you please assist. Thanks
Ajmal Shaikh

**Comment by ibmmqmet** [comment]
The error message you are reporting here shows that the MQ client libaries have not been installed on the image. 

There's no way to tell from here WHY those client libraries are not installed as you have not included that information. 

For linux/x64 systems, the postinstall script will usually try to download the libraries and unpack them. If your system is running in an environment without access to the public download site, or if you are trying to access older versions of the MQ client library that are no longer on the IBM download site, then you will need to manually put the libraries into your container image and disable the postinstall script from trying to execute the download. Set the `MQIJS_NOREDIST` environment variable to any value.

**Comment by chughts** [comment]
This looks like npm doesn't like the certificate on `nexus.iw-bld.oncp.dev`

As the warning log hints you should be able work around by setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to `0`

**Comment by ibmmqmet** [comment]
That also looks like you might have edited the postinstall script to download from your own site. (The 1.0.4 version didn't allow custom URLs.) If you are running the postinstall directly instead of as part of the full npm install process, then perhaps you're not running it in the right directory. Running the app with the environment variable MQIS_TRACE ought to show where the code is trying to load libmqm from. And then you can check it's correctly installed.
