### ISSUE TITLE
403 Forbidden for the MQ C library

### ISSUE THREAD

**Issue by jkltong** [ibm-messaging/mq-mqi-nodejs#170]
Issue:
Unable to download the IBM MQ C library from
[https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev]()
It is returning 403 forbidden.

I understand that this issue may not be related to this repo, but could we receive some assistance with this problem? Thank you in advance!

**Comment by ibmmqmet** [comment]
There's nothing I can do, but I understand it's being looked at - it's a broader issue than just these files.

**Comment by jkltong** [comment]
It seems to have fixed again now. No sure if it will be a persistent problem.
