### ISSUE TITLE
Why is getCB called twice?

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#18]
Hi
Maybe a stupid question: I run the sample amqsput.js and then afterwards amqsgeta.js. In the amqsgeta.js file I can see that I enter getCB() twice, first to to display the message and then later to display "No more messages available". Why do I enter getCB twice? The program calls mq.Get(queueHandle,md,gmo,getCB) only once, so I would expect the callback function getCB to be called only once.

Thanks, Morten

**Comment by ibmmqmet** [comment]
This is expected. The call to Get sets up the callback which will then be invoked for all arriving messages that match the criteria. To cancel the callback for further messages, use the GetDone() function. This is essentially the same behaviour as the underlying MQCB/MQCTL operations in the core MQI library.
