### ISSUE TITLE
What are the plans for mq-mqi-nodejs?

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#2]
Hi. I need to Interface my node.js Application to IBM MQ, hence I am interested in mq-mqi-nodejs. Are there plans to make it public on npm and if so, when?
Thanks Morten

**Comment by ibmmqmet** [comment]
As the README shows, NPM is something I'm considering for the future. But want to give it a bit of a shake-down first before going to that step. While that will make it more convenient eventually, you don't need to use NPM to get this now as you can clone this repo directly.
