### ISSUE TITLE
'Add callback function to getCB'?

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#20]
Hi
Maybe my thinking is wrong, but please comment:
From the sample, amqsgeta.js:

function getMessages() {
..  mq.Get(queueHandle,md,gmo,getCB);    ..
}
function getCB(err, hObj, gmo,md,buf) 

So the callback function has the following parameters: err, hObj, gmo,md,buf
I'm thinking. Would it make sense to add a callback function to the list above? So the list would be: err, hObj, gmo,md,buf,cb ?
In this way getCB could be part of the MQ 'driver' and the callback function, cb, would live in the web application layer (in a different file) and only be concerned with the message itself. 

Morten

**Comment by ibmmqmet** [comment]
I don't think I see what you're trying to get at here. The getCB function in amqsgeta shows how a callback is registered and driven, but there's already a function (mqiCB) inside mqi.js that is calling that callback, and setting up the various parameters. What you do in your application equivalent of the getCB sample is up to you, based on the parameters passed to it.
