### ISSUE TITLE
connection pool

### ISSUE THREAD

**Issue by dkuida** [ibm-messaging/mq-mqi-nodejs#21]
A general question
I believe it is logical to hold a connection open whilst the application is alive, would it make sense to have a conneciton pool ?

**Comment by ibmmqmet** [comment]
Connection pools are sometimes implemented in higher layer components - for example JEE in a Java App Server will manage connection pools for short-lived EJBs. It's not an piece of the core MQI though so I've not tried to invent one here.

**Comment by freerider7777** [comment]
So how many connections to MQ are opened by the application? Single connection?
