### ISSUE TITLE
Error when calling: mq.Get(queueHandle,md,gmo,getCB)-

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#22]
I'm opening this one, because I'm not sure if you have read my latest comments to #17. I've been working quite a lot on it, but I'm still stuck. And now I'm running out of time. I'm wondering, could there be a bug in ibmmq? I need some help to debug it.
Thanks
Morten

**Comment by ibmmqmet** [comment]
added comment to #17
