### ISSUE TITLE
Typo in checkParam for MQPUT1

### ISSUE THREAD

**Issue by ravellan** [ibm-messaging/mq-mqi-nodejs#23]
https://github.com/ibm-messaging/mq-mqi-nodejs/blob/ba1866e54de553351978bb275c0245cc5163067f/lib/mqi.js#L1035
Found a small typo, variable should be `jsod`.

While I'm here I just want to say thanks for all the work done so far on bringing this to the community. This is the only issue I've found so far.

**Comment by ibmmqmet** [comment]
Thanks for the comment. That should be fixed in the version I just pushed.
