### ISSUE TITLE
Getting exception when doing npm install ibmmq

### ISSUE THREAD

**Issue by loudywen** [ibm-messaging/mq-mqi-nodejs#24]
`4 warnings and 10 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/diwenlao/Documents/GitHub/nodejs3/node_modules/ffi
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN nodejs3@1.0.0 No description
npm WARN nodejs3@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by ibmmqmet** [comment]
You need to look at the errors above the piece you have pasted here. Presumably something missing in your compiler/toolchain setup that means native code cannot be compiled. That's not something really to do with this package.

Though there's no regular MQ client library for Darwin so you may then hit a different problem...

**Comment by loudywen** [comment]
@ibmmqmet  ya. i fixed it by setting the correct python path

**Comment by angadalasunilyadav** [comment]
@loudywen I’m facing the same issue what you faced with nodejs IBMMQ installation. Please let me know the steps to setup the python path?
