### ISSUE TITLE
How to setup the hostname and port and channel, etc..?

### ISSUE THREAD

**Issue by loudywen** [ibm-messaging/mq-mqi-nodejs#25]
Hi Mark, can you please tell me how can I setup host name, port and channel name? From your sample, I don't see you setup these parameter. By the way, I am a Java guy, I know how to code it in Java to interact with MQ. But we have new requirement and want to build nodejs - mq application. So I am trying to explore how Nodejs work and also your ibmmq module.

**Comment by ibmmqmet** [comment]
It's done in essentially the same way as for the C client - environment variables like MQSERVER, or use the CCDT, or programmatically using the MQCD structure passed to the ConnX verb.

See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q027440_.htm for more details. This Node package does have the MQCD structure available. So it would be something like

```
var cno = new mq.MQCNO();
cno.Options = MQC.MQCNO_CLIENT_BINDING;
var cd = new mq.MQCD();
cd.ConnectionName = "localhost(1414)";
cd.ChannelName = "SYSTEM.DEF.SVRCONN";
cno.ClientConn = cd;

mq.Connx(qMgrName, cno,  ....
```

**Comment by loudywen** [comment]
@ibmmqmet  thx . i will try.

**Comment by loudywen** [comment]
hi @ibmmqmet , when i try to run it with the code snippet u gave. I am getting these error:
` → C:\nodeJs\demo1\node_modules\ref\build\binding.node
 → C:\nodeJs\demo1\node_modules\ref\build\Debug\binding.node
 → C:\nodeJs\demo1\node_modules\ref\build\Release\binding.node
 → C:\nodeJs\demo1\node_modules\ref\out\Debug\binding.node
 → C:\nodeJs\demo1\node_modules\ref\Debug\binding.node
 → C:\nodeJs\demo1\node_modules\ref\out\Release\binding.node
 → C:\nodeJs\demo1\node_modules\ref\Release\binding.node
 → C:\nodeJs\demo1\node_modules\ref\build\default\binding.node
 → C:\nodeJs\demo1\node_modules\ref\compiled\6.9.4\win32\x64\binding.node
    at bindings (C:\nodeJs\demo1\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\nodeJs\demo1\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\nodeJs\demo1\node_modules\ibmmq\lib\mqi.js:59:11)`

**Comment by ibmmqmet** [comment]
google suggests you have a problem with the node-gyp build steps. perhaps something needs to be rebuilt or recompiled. Maybe your previous build problems from #24 left something in a partial state.
