### ISSUE TITLE
How can I set SSLCipherSuite?

### ISSUE THREAD

**Issue by loudywen** [ibm-messaging/mq-mqi-nodejs#26]
@ibmmqmet  how can I set SSLCipherSuite("TLS_RSA_WITH_AES_128_CBC_SHA256")?

**Comment by ibmmqmet** [comment]
SSLCipherSpec is a field in the MQCD structure. See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.ref.dev.doc/q108220_.htm
