### ISSUE TITLE
How to setup thread?

### ISSUE THREAD

**Issue by loudywen** [ibm-messaging/mq-mqi-nodejs#27]
hi @ibmmqmet  I know there is no thread concept in Node.js. But in java I can spawn up for example 30 threads to listen on the queue to increase the performance. So in you package do you have thing like this?

**Comment by ibmmqmet** [comment]
In Node, everything runs on the same execution thread. While you could have multiple open handles to a queue, the GETs would all be serialised on the same thread so there's not likely to be any benefit - you can't have parallel work going on in the same process.
