### ISSUE TITLE
The async Get() and performance

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#29]
Hi
I would like to come back to Issue 17 and the new async Get() implementation. As I said, my put-get program now works fine and I have been able to demonstrate this to my collegues. I’m really happy bout that. Thanks. 
My next concern is performance. Will the new async Get() make things slow? What happens when I call Get() quickly one after another? 
I’m wondering if this is correct: The first Get() will get the CPU for a little bit and then leave the CPU so that it can process the next ting on the stack. Then after a second the first Get() will get the CPU again. It will poll the MQ queue. If it is able to read something, the callback function started. If not, it will leave the CPU again so that the CPU can start the next thing on the stack, and so forth. Is this correct?
Thanks
Morten

**Comment by ibmmqmet** [comment]
I think you've basically understood how it works - when you call Get() the first time, there will be an immediate test to see if there is a message so no delay when there's something already waiting. And only after that will there be the poll loop.

Polling is never going to be as efficient as a blocking wait (which is bad to use in Node, but common elsewhere) or having the callback driven directly on the arrival of a message. But it should not be too bad unless you are trying to do something like matching a msgid/correlid or other message property on a very deep queue. You might want to tune the poll timer to be longer than a second, depending on the expected arrival rate of messages on the queue, but that's best discovered by testing with real workloads. Some similar solutions I've seen set the equivalent timer to about 30 seconds. 

I'm thinking about some kind of adaptive timer for the loop, possibly different timers for each queue if you are reading from multiple queues, but I don't want to make it too complicated.

**Comment by mortenLom** [comment]
Thanks and thanks for letting me know that my thinking was right. 
I have two implementations of an MQ client, one written in Node.js using mq-mqi-nodejs (the one I have been working on) and one written in Java using JMS (a collegue of mine has written). My plan is to do some load testing and compare the two. Any guess on which one will win? 
I can also experiment a little with different poll intervals. 
Do you know if somebody else has done a similar comparison and written something on it?
Thanks.
Morten

**Comment by ibmmqmet** [comment]
Performance of MQ overall will depend very heavily on the specific workload, in particular how much work is being done in parallel from different applications, with items such as persistence and transactions being part of the considerations. Just running a single application, for example, is useless for measuring overall system performance.  And of course it depends on what you are trying to measure - latency, number of messages per second, CPU costs etc. You can see the kinds of performance numbers we get for specific scenarios [here](http://www-01.ibm.com/support/docview.wss?uid=swg27007150#1) 

But noone's published anything about this package's performance and I would not expect them to.

**Comment by mortenLom** [comment]
Yes, I was thinking about a) round-trip-time (latency) and b) number of messages per second.

When I tested with 0.3.5 the callback function from getMessage was called +1s after I called getMessage:
  debugInfo:putget getMessage: start +275ms
  debugInfo:putget getCB: start +1s

When I upgraded to 0.3.7, this was reduced to 16ms:
  debugInfo:putget getMessage: start +281ms
  debugInfo:putget getCB: start +16ms

So this is good news for round-trip-time. It consider it to be The next thing I want to check out is what happens when I send many packet per second to my node.js program. Will the first packet block for the other packets that follow. I will come back on this.

**Comment by mortenLom** [comment]
Number of packets per second is probably more a Node.js characteristic than an ibmmq characteristic. Therefore I close this ticket. Instead I can open a new one later if I still have questions on performance. Thanks for all the help. I have a much better understanding now.
Morten
