### ISSUE TITLE
IP address and port of the MQ endpoint

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#3]
Hi. I have looked at the sample code. I would like to try it towards an MQ endpoint on another machine. I see that I can enter queue manager and queue as command line inputs, but where/how do I enter the IP address and port?
Thanks
Morten

**Comment by ibmmqmet** [comment]
As the README says, you should use the MQSERVER environment variable as the simplest way to point the package at a remote queue manager. See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.con.doc/q016990_.htm for the format.
