### ISSUE TITLE
MQRC_Q_MGR_NAME_ERROR [2058]

### ISSUE THREAD

**Issue by mangeshshete** [ibm-messaging/mq-mqi-nodejs#31]
We successfully able to connect IBM MQ using java client. Please check below JAVA code.

```
private void init(String hostName,String port, String qMngr,String channel){
	 MQEnvironment.hostname = hostName;
	 MQEnvironment.channel = channel;
	 MQEnvironment.port = Integer.valueOf(port);
	 MQEnvironment.properties.put(CMQC.TRANSPORT_PROPERTY, CMQC.TRANSPORT_MQSERIES_CLIENT);
	 MQQueueManager qManager = null;
	 try {
		qManager = new MQQueueManager(qMngr);
		System.out.println("### Connection Successful for host : "+hostName);
	} catch (Exception e) {
		e.printStackTrace();			
	} finally {
		try {
			qManager.disconnect();
			qManager.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

But when we are trying connect using sample (amqsconn.js) file, we are getting below error.
We have provided appropriate details which is working with JAVA client. 

Error: 

`MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_Q_MGR_NAME_ERROR [2058] [Pkg ver = 0.4.1] `

**Comment by ibmmqmet** [comment]
There's nothing obvious showing what's wrong here - maybe an MQ trace would show what is actually being requested from the client. Are you sure you've got the right value for the ConnectionName field which combines the hostname and port number. And remember that the qmgr name is case-sensitive.
