### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#34]
Hi
I'm trying to make a Docker container consisting of MQSeries Client, nodejs, your ibmmq and my own nodejs application, but have not succeeded yet. Has anyone made a Docker container consisting of MQSeries Client and ibmmq? And in a clever way so that the container is as small as possible? I would be very interested to see how the Dockerfile would look like.

Thanks for any help.
Morten

**Comment by ibmmqmet** [comment]
In what way have you "not succeeded"? The MQ client code that is needed for runtime is now available via a simple download from [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/) which should make it relatively easy to pull into a container and unpack.

**Comment by james-r-smith** [comment]
@ibmmqmet, I know that this is a different situation than for [Golang](https://github.com/ibm-messaging/mq-golang/issues/24), as the SDK is needed for the compilation step, but is the client code needed for runtime for Golang the same as the link you provided above.

In addition to that question, is the client code supplied able to run in Alpine Linux? Thanks!

**Comment by ibmmqmet** [comment]
The MQ client runtime code required is the same for both go and node. 

I don't know anything about Alpine Linux, but when I looked it up, I saw

> Alpine Linux is built around musl libc 

and

>  musl, which is partially binary compatible with glibc

which sounds a bit worrying. The MQ code is, of course, compiled against the glibc and other relevant libs from one of the formally supported distros. So anything that is not compatible with that is unlikely to work.

**Comment by james-r-smith** [comment]
Dang, okay, yeah I knew that Alpine used musl libc, which is a big issue for Java users who desire small, containerized applications as well. That's great news to hear for the runtime code, though.

I can test later to see, but even if the results are positive, it still might not be a good idea to use it anywhere other than for tests. Do you know if MQ is looking to support Alpine Linux in the near future?

**Comment by ibmmqmet** [comment]
Definitely no plans to support Alpine. It's never even been mentioned before that I know of. And it's not just libc ... the TLS stuff relies on some C++ runtime too. And there's dynamic loading via dlopen going on potentially too. Chances of binary compatibility seem rather small.

**Comment by james-r-smith** [comment]
Okay, I'm also seeing [busybox](https://github.com/spritsail/busybox) as another possible alternative, though the non libc items that you are listing could also affect this route. 🤔

**Comment by mortenLom** [comment]
"The MQ client code that is needed for runtime is now available via a simple download from here ..". Does that mean that I don't need to install MQSeriesRuntime-9.x.x.x.x86_64.rpm and MQSeriesClient-9.0.0.0.x86_64.rpm? (When I tested ibmmq earlier I had those two RPM packages installed)

**Comment by mortenLom** [comment]
I am now able to run my node.js application in a Docker container. My concern now is that my Docker image is quite large, approx. 840 MB. Is there a way to get it smaller? Thanks for any help. 
I have included my Docker file. 
Dockerfile.txt](https://github.com/ibm-messaging/mq-mqi-nodejs/files/2017366/Dockerfile.txt)
Morten

**Comment by ibmmqmet** [comment]
A lot of stuff in the redist client package is not needed to run these applications. That might help though I've not measured how much space it would save. There is a genmqpkg.sh command included in there that can be used to repack the tar file (it's interactive but could be driven by something piped from stdin) into including just the pieces you need for specific requirements - eg get rid of java, bin and samp directories.

I was actually experimenting earlier today with doing something like automatically including relevant parts of the redist package as part of the "npm install" process but it's not ready for anyone else to try.

**Comment by ibmmqmet** [comment]
I've just pushed a Dockerfile as an example, along with an update that automatically installs the MQ C client libraries. Careful structuring of that Dockerfile file keeps the image to about 410MB - basically do all the RUN steps in one line, includng the uninstall steps to clean up.

**Comment by mortenLom** [comment]
Wow. Thanks, I have tested your demo Dockerfile and it works fine. I also get about 410MB. I will look more closely at it so that I understand it all.

**Comment by mortenLom** [comment]
Now I have made a Docker image of my own application based on your Dockerfile and that works fine too. My image size is now 541 MB, down from 840 MB, so that's very good.
One question. In your Dockerfile you have:
# This is a queue predefined in the MQ Developer Edition server container
ENV DOCKER_Q    DEV.QUEUE.1
ENV DOCKER_QMGR QM1
I am puzzled that you define environment variables for a queue? I thought I was only getting an MQ client, not an MQ queue (server). Or am I wrong?
Thanks
Morten

**Comment by ibmmqmet** [comment]
I was able to reduce the container by another 100MB by basing the image off debian:jessie-slim ... will use that next time I push.
