### ISSUE TITLE
Unable to run samples

### ISSUE THREAD

**Issue by sumitpramanik** [ibm-messaging/mq-mqi-nodejs#36]
Please include the following information in your ticket.

- mq-mqi-nodejs version(s) that are affected by this issue.
- A small code sample that demonstrates the issue.
Hi there,
I tried running the samples as mentioned in the Read.me file, but couldn't get it up and running.

if (inspect.name === 'refinspect') {
             ^

TypeError: Cannot read property 'name' of undefined
    at overwriteInspect (/Users/SP/Desktop/Repos/mq-mqi-nodejs/node_modules/ref/lib/ref.js:1455:14)
    at Object.<anonymous> (/Users/SP/Desktop/Repos/mq-mqi-nodejs/node_modules/ref/lib/ref.js:1417:32)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

I have installed the ibmmq mocule. I don't have the MQ Client libraries though and that is because there is none for mac os and I suspect that is causing the issue.

How do I get it up and running on mac ?? Any help would be appreciated.
(Please note: I am fairly new to MQ and IBM MQ)

Thanks,
SP

**Comment by sumitpramanik** [comment]
I was able to resolve this issue by upgrading the version of node.js from 6 to 8. But now stuck at this 

Cannot find MQ C library.
  Has the C client been installed?
  Have you run setmqenv?

Error: Dynamic Linking Error: dlopen(/opt/mqm/lib/libmqm_r.dylib, 2): image not found

Does someone have a clue how do I get the libraries installed on mac ?

**Comment by ibmmqmet** [comment]
There are currently no publicly available MQ client libraries for Mac. The alternative way of running MQ code on that platform is to put it inside a Linux container.

**Comment by ibmmqmet** [comment]
Closing this as there is nothing that can be done in this repo about Mac support.
