### ISSUE TITLE
Unzip not a native command in Windows

### ISSUE THREAD

**Issue by ravellan** [ibm-messaging/mq-mqi-nodejs#38]
https://github.com/ibm-messaging/mq-mqi-nodejs/blob/ba41a92d9671bc828b6a9d438882dce52c869df4/postinstall.js#L99
AFAIK `unzip` is not a native command in Windows. I fiddled around with Expand-Archive available in Powershell 5+ (Win10/Server 2016) and got this to work.

`unpackCommand='powershell.exe -Command "Expand-Archive -Path ' + file + ' -Destination .\\' + newBaseDir + '\"'`

**Comment by ravellan** [comment]
Yes Powershell 5 is not the default in Win7 so node package sounds like the right approach. I do most of my dev work on Windows so I will discover things quite quickly.
Another thing that might be worth considering. I already have the MQ client globally installed in my dev environment so it would be nice to have a check for this and not download the client for every new project folder. Perhaps a check for an env variable like MQ_FILE_PATH might be sufficient?

**Comment by ibmmqmet** [comment]
Yes - I already put in a check earlier this morning to allow disabling of the download. And then it would rely on PATH/LD_LIBRARY_PATH to find an already-installed version.

**Comment by ravellan** [comment]
Tested the new unzip and MQIJS_NOREDIST and they both work as expected. Thanks for the quick response.
