### ISSUE TITLE
Do I need to install MQ V9?

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#4]
1. Maybe a stupid question. Do I need to install MQ V9 in order to run the samples? I find it strange, because, isn't MQ for the server side, whereas ibmmq is for the client side?
2. I have installed mq-mqi-nodejs on CentOS. I can see that there now is a directory: /usr/lib/node_modules/ibmmq. However, when I run the sample, I still get "Cannot find module 'ibmmq'. Do you know why?

**Comment by ibmmqmet** [comment]
You certainly need to install at least an MQ product client package. This package is a layer on top of the C libraries. Hence the use of the ffi package to access it.

I don't know why you can't find the package from the samples. I guess you've not done a suitable "npm link" from the right directory but each environment I've tried has been slightly different.

**Comment by mortenLom** [comment]
Thanks. But I still have lots of questions. I'm a little new to node.js and more.
1. How do I install this MQ product client package you mention? Can you direct me to a web page where I can download it? I am running node.js on CentOS
2. I have tried the node.js module "mqlight". Do I understand correctly, that if I were to use mqlight instead of your ibmmq, the MQ server (at the other end) needs to be configured differently? Since, in that case, the message format will be different. It will be an amqp message format and will have to be treated differently. Am I right?
