### ISSUE TITLE
Is MQCONN and MQOPEN needed  for every REST call

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#40]
Maybe a stupid question. I have made a Node.js web server which exposes a REST API. Typically it receives a REST call, then sends a message to a MQ queue on another machine, then receives a reply from another MQ queue and responds to the REST call. I was wandering. Do I need to call MQCONN and MQOPEN following by MQCLOSE and MQDISC for very REST call? Or could my web application just call MQCONN and MQOPEN once at start up and then just leave it open for as long as the web application is running?
Thanks
Morten

**Comment by ibmmqmet** [comment]
Best practice is to MQCONN as few times as possible as it's an expensive operation. So connect to the queue manager at startup (and be prepared to reconnect in the event of a connection failure). If you are continually using the same queue, then just open that once too.

**Comment by calmeyda** [comment]
Hi I keep connections and queues open, but how may I handle on disconnect? I get an error "parameter of type mqobject must be provided", exists any event so I can detect a disconnect?
