### ISSUE TITLE
Is it possible to convert MQ-Metrics-sample to this nodejs?

### ISSUE THREAD

**Issue by edperry** [ibm-messaging/mq-mqi-nodejs#43]
I wrote a long time ago a simple JAVA app to monitor MQ 8,  it still works but is really slow.

I would rather not add yet another programming language on my nagios system (GOLANG) and was hoping it was possible to use mq-mqi-nodejs  to implement a NodeJS version of the MQ-Metrics?

(OR Maybe I just overlooked it in this repo)

**Comment by ibmmqmet** [comment]
There's nothing in this repo that would directly handle the metrics. I've not written JS  functions to work with MQ's published resource statistics in the same way as I did for Go. It doesn't feel like it would be a common use case for a JS program.

While I'm sure it would be possible to write the equivalent functions, both to manipulate PCF messages and to work with whatever APIs are needed for the monitoring agents, you'd have to build it all by hand. Remember though, that MQ now has REST APIs for equivalents of MQSC commands so depending what metrics you were interested in working with, you may be able to use those.
