### ISSUE TITLE
Get qMgr/qName from CCDT

### ISSUE THREAD

**Issue by orweinberger** [ibm-messaging/mq-mqi-nodejs#46]
I'm able to run a sample that will use a CCDT file to successfully connect to a queue, however, is it possible to execute `mq.Conn` without defining a qMgr and the qName as the queue manager and queue name are already defined inside the CCDT file? 

When I try to remove it or place an empty value it throws an error message.

**Comment by ibmmqmet** [comment]
The CCDT has nothing to do with queues - only qmgrs. There's lots of information about how CCDT lookups work in [the KC](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q027580_.htm)

In summary, you can create a CCDT entry with an empty qmgr name, and that can be matched by an empty qmgr name in the application. There are then various things that can be done when putting a leading asterisk (don't think of it as a real wildcard) on the qmgr name in the app.

In this node package, you can pass null or "" to the Conn verb as the empty name.
