### ISSUE TITLE
Working with SSL certificates

### ISSUE THREAD

**Issue by orweinberger** [ibm-messaging/mq-mqi-nodejs#47]
I've successfully connected to a queue through a non-encrypted channel using a CCDT file and I am able to read messages correctly.

I'm now attempting to use a secure channel via CCDT and wondering if I should just be defining the `MQS_KEYSTORE_CONF` env variable and everything should work? Another question, is it possible to use this node module along with JKS?

**Comment by ibmmqmet** [comment]
The environment variable to use is MQSSLKEYR. See [docs here](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q017060_.html)

MQS_KEYSTORE_CONF is used for Advanced Message Security configuration. It's a config file that in turn points at keystores and other values.

The gskit libraries underpinning this package only deal with KDB formats. Some of the command line tools will process JKS stores for convenience, but it's not been enabled for the C library runtime.

**Comment by orweinberger** [comment]
Thanks @ibmmqmet, I'm using the `MQSSLKEYR` to refer to the KDB path in the correct manner (defining the path without extension). I have both the `kdb` and `sth` files in the same directory and using the same base file name. I'm getting an error message saying `MQRC_KEY_REPOSITORY_ERROR [2381]` even though I'm able to use the mq client cli tools to connect successfully using these files.

I'm wondering if this has something to do with the `KeyRepository` configuration as it mentions it in the documentation. Is there an example on how to set this value using this module?

**Comment by ibmmqmet** [comment]
Assuming you have mykey.kdb, .rdb and .sth along with the CCDT, then you should be able to run with no code changes at all. The kdb must include the signing information for the qmgrs cert to validate that, and - if the SSLCAUTH setting on the svrconn requires it - the client's certificate with an appropriate label. See [here](http://www-01.ibm.com/support/docview.wss?uid=swg21245474) for a lot more detail on that. 

And of course make sure the CLNTCONN definition matches the SVRCONN definition for cipherspec. 

Error log entries from both the queue manager and the client can give much more information than the simple MQRC value.

I do have a sample that I need to tidy up for doing TLS completely programmatically where the CD, SCO and CNO structures are involved but you don't need that when you use the CCDT.

~~~
export MQ_CONNECT_TYPE=CLIENT  # This may not be needed but it forces client connections
export MQSSLKEYR=`pwd`/mykey # Assume things are all in current directory
export MQCHLLIB=`pwd`
export MQCHLTAB=AMQCLCHL.TAB

node amqsput
~~~~

I will often run programs under strace just to check that the correct files are being successfully opened; it's the quickest way to verify some of the environment variables are taking effect. And MQ trace would be more detailed debug.
