### ISSUE TITLE
MQ Error 2009 if /home/{user}/IBM folder is not present or no write permissions on the directory

### ISSUE THREAD

**Issue by diegoh** [ibm-messaging/mq-mqi-nodejs#49]
We are trying to deploy to a server where we can't add new directories.
Is there a way to change this path or disable this completely?

**Environment:**
- Version 0.7.1
- MQ Redist libs version 8
- User is the user running the node service.

**Sample code:**
This happens if there are any errors using the library.

**Comment by ibmmqmet** [comment]
The MQ client library (and here we are really talking about the underlying product code, not this node wrapper) expects to be able to write things like error messages and FDC logs somewhere. The default directory root can be changed with the MQ_OVERRIDE_DATA_PATH environment variable so it doesn't have to be under /home/user, but the C runtime still needs to be able to write to that chosen path.

**Comment by diegoh** [comment]
Great, thanks!
