### ISSUE TITLE
MQGMO_WAIT is blocking execution

### ISSUE THREAD

**Issue by freerider7777** [ibm-messaging/mq-mqi-nodejs#50]
If I put MQC.MQGMO_WAIT  instead of MQC.MQGMO_NO_WAIT as in examples, Node freezes 
In such places:
  gmo.Options = MQC.MQGMO_NO_SYNCPOINT |
                MQC.MQGMO_NO_WAIT |
                MQC.MQGMO_CONVERT |
                MQC.MQGMO_FAIL_IF_QUIESCING;

So I have to request for messages in a loop which makes a delay in receiving from the queue...

**Comment by ibmmqmet** [comment]
Have you read in the README and the samples about the difference between the Get and GetSync functions?

**Comment by freerider7777** [comment]
Thanks! I took the first sample for examination :) I'll try the second.
