### ISSUE TITLE
Unable to browse queue messages.

### ISSUE THREAD

**Issue by rohitjain31** [ibm-messaging/mq-mqi-nodejs#54]
Here i used Get or Getsync method after connecting to the MQ but messages are deleted from queue if we use these methods.
I just need to fetch messages. Please guide.

**Comment by ibmmqmet** [comment]
Destructive GET is the normal, default behaviour for message retrieval in MQ. 

If by "fetch" you mean "browse", then use the MQGMO_BROWSE_FIRST or MQGMO_BROWSE_NEXT flags to the GetSync operation. Browsing via async consumer is possible, but resetting those flags needs a bit more work in the application.

**Comment by rohitjain31** [comment]
Thanks buddy.

I am using this GMO option.
**gmo.Options = MQC.MQGMO_BROWSE_FIRST | MQC.MQGMO_NO_WAIT | MQC.MQGMO_FAIL_IF_QUIESCING;**

Problem is that here i am getting the first message only, not able to browse all messages and i am trying to achieve this in Nodejs.
