### ISSUE TITLE
Cipher Spec does not work

### ISSUE THREAD

**Issue by andreasschacht** [ibm-messaging/mq-mqi-nodejs#55]
Hello,

I'm using the v.0.9.2 and I got a `MQRC_SSL_INITIALIZATION_ERROR [2393]` - error when I just change the ssl cipher spec from `TLS_RSA_WITH_AES_128_CBC_SHA256` to `ECDHE_RSA_AES_256_CBC_SHA384`

A short snippet:

```
import mq, { MQC } from 'ibmmq';
import { promisify } from 'util';

export default class SSLConnector {

  /**
   * Connect to queue manager with ssl
   *
   * @returns {Promise.<MQQueueManager>}
   * @public
   */
  static getConnection(config) {
    // Do the connect, including a callback function
    let qMgr = config.queueManager.name;
    let cno = new mq.MQCNO();
    cno.Options |= MQC.MQCNO_CLIENT_BINDING;

    let cd = new mq.MQCD();
    cd.ConnectionName = config.connectionName;
    cd.ChannelName = config.channelName;
    cd.SSLCipherSpec = config.ssl.sslCipherSpec;
    cd.SSLClientAuth = MQC.MQSCA_OPTIONAL;

    // Make the MQCNO refer to the MQCD
    cno.ClientConn = cd;

    let sco = new mq.MQSCO();
    sco.KeyRepository = config.ssl.keyRepository;
    cno.SSLConfig = sco;

    return promisify(mq.Connx)(qMgr, cno);
  }
}

```

Do I miss some additional requirements? Is there a way to get a more details of the error than just a generic error message?

**Comment by fjbsaper** [comment]
You did not specify, but unlike Https, MQ requires the cipher spec at both ends of the channel to match.
So if you switch your client connection channel cipherspec to a new value, make sure that the corresponding server connection channel has the same cipher spec.

On the other hand you did not specify the key size of your RSA key. Some high key sizes have become mandatory to be able to use some of the more exotic cipherspecs...

Hope it helps

**Comment by ibmmqmet** [comment]
See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.sec.doc/q010240_.htm for requirements on the certificate when using elliptic curve ciphersuites. I'd also expect there to be more info in the MQ error logs.

**Comment by andreasschacht** [comment]
@fjbsaper @ibmmqmet That helped, thank you very much. Found out that the server side was misconfigured. But still have the question, is it possible to enable somethings like a debug mode to get further details? Maybe it would be helpful for future questions.

**Comment by ibmmqmet** [comment]
There's no further debug information available from the underlying libraries, other than turning on the MQ trace. That would probably show a lot more information than is helpful, and is not meant to be used regularly by anyone other than IBM service anyway - though it would show the information that gets written to the local error log.

**Comment by andreasschacht** [comment]
The docs ttps://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.tro.doc/q039570_.htm mentions that there should be an error log at `/var/mqm/errors` on client side, but unfortunately isn't in my case...

**Comment by andreasschacht** [comment]
I'll close this issue, because it's not an issue of this project. Thanks for your help!
