### ISSUE TITLE
how to setup multiple ip (for ha cluster with 2 nodes)?

### ISSUE THREAD

**Issue by freerider7777** [ibm-messaging/mq-mqi-nodejs#56]
Hello!

What is the recommended way to configure for HA cluster with 2 ip addresses?

Thank you!

**Comment by freerider7777** [comment]
difficult to find on ibm site, but it seems I can just 
mqcd.ConnectionName to multiple comma separated ip(ports)

**Comment by ibmmqmet** [comment]
Yes. It's the same syntax as MQSC for the CONNAME: https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q085170_.htm#q085170___conname
