### ISSUE TITLE
Need some help/advice

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#6]
Hi
This is a follow-up on the previous issue. (I create a new one, because the previous issue was closed).
I'm struggling a bit. I'll be happy for any advice. My situation is the following: I have a MQ server running on mainframe (z/OS). It has a Queue Manager and two Queues, one for each direction. I also have an MQ client running on mainframe that reads and writes to these queues. This is up and running and working. 
Now I want to establish another MQ client at the other end, running on a different machine, Linux - CentOS, and using node.js. I have followed two approaches: 1) ibmmq  and 2) mqlight. The problem with 1) is that it is not official and I get execution errors when I run the samples. My last status on is that the command 'node-gyp rebuild' fails when I run it as root. I get:
gyp: binding.gyp not found (cwd: /etc) while trying to load binding.gyp. I am also puzzled that there is a node-gyp both in /bin and in /usr/bin. Do I have two installations?
My latest status on mqlight, is that I am not sure if MQ server running on mainframe (z/OS), supports AMQP. If not, I can rule out mqlight. Do you know?
I will be happy for any advice. Is the way forward for me, ibmmq or mqlight? Or would you recommend REST API.
Thanks for any help.
Morten

**Comment by mortenLom** [comment]
I am connecting to a server running MQ z/OS v9.0.0. This does not support AMQP, Hence MQ Light is not an option for me. 
The way I see it, I'm left with ibmmq or REST API. However, REST API is not supported on MQ z/OS v9.0.0. It needs to be upgraded to v9.0.4. No so easy this ..

**Comment by ibmmqmet** [comment]
if you want to write your app for a node environment and connect directly to a z/os queue manager, then these are your choices for now. if you introduce another qmgr running on a different platform, then mqlight could be an option - publications could be sent from that qmgr to z/os. But you will have to select the correct architecture based on all the usual requirements and constraints from your organisation.
