### ISSUE TITLE
MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]

### ISSUE THREAD

**Issue by QiluXie** [ibm-messaging/mq-mqi-nodejs#62]
Please include the following information in your ticket.

- **mq-mqi-nodejs version(s)**: 0.9.5
- **MQ Client Version:** 9.1.2.0
- **MQ Server Version:** 8.0.0.9
- **Issue description**
I'm using Nodejs client and try to establish SSL connection to MQ Server. I followed the sample code of [amqsconntls.js](https://github.com/ibm-messaging/mq-mqi-nodejs/blob/master/samples/amqsconntls.js) exactly. I've got all 4 keystore files (.kdb, .sth, .rdb, and .crl), but always got the following error:
`error: {"name":"MQError","message":"CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]","mqcc":2,"mqccstr":"MQCC_FAILED","mqrc":2393,"mqrcstr":"MQRC_SSL_INITIALIZATION_ERROR","version":"0.9.5","verb":"CONNX"}`

- **Questions**:
1. I've tried using a dummy .kdb file and also got the same above error code. Is there any way to see more detailed error message from Client side? It looks like the error code 2393 cannot even determine if the request reaches MQ Server or not. 
2. What could possibly cause the above error? Is it possible that something is wrong with the .kdb file? Is there any way to validate the .kdb file from client side?

Any help is highly appreciated! Thanks a lot.

**Comment by ibmmqmet** [comment]
There may be more information in a client-side error log (AMQERR01.LOG). Assuming there was some contact with the server, then there should be real details of the failure in the queue manager's error log. 

Most common reasons for the failure are probably a mismatch of CipherSpec or something missing in the certificate chain such as the client not having the signer's cert required to validate the server's cert.

**Comment by QiluXie** [comment]
Thanks a lot @ibmmqmet . Two follow-up question: 
1. I couldn't find AMQERR01.LOG on client side. Is there any specific way to enable this client-side logging? (I did find these log files on Server side though)
2. In our previous testing, without SSL implementation, server side was able to see contact from client side (though it also gave the same SSL Init error 2393). But with SSL implementation, server side was not able to see any contact from client side. What would be the most probable cause in this case? Is it implying that something is wrong in the .kdb database files?
I will have another working session with middleware team to check if the request reaches server or not. Will keep you posted. 
Thanks!!!

**Comment by QiluXie** [comment]
@ibmmqmet I've resolved it by setting the SSLkeyrepository and certificatelabel in mqclient.ini configuration file on the server. Somehow supplying those two parameters in the nodejs code didn't work. (I double checked that keystore files are in the same folder of the code).
Would recommend to add certificateLabel in the code sample [amqsconntls.js](https://github.com/ibm-messaging/mq-mqi-nodejs/blob/master/samples/amqsconntls.js)
Thanks!

**Comment by ibmmqmet** [comment]
The amqsconntls program deliberately does not send a client certificate - the SSLClientAuth field is set to only require that the server certificate be validated. It makes it simpler for a sample, as you don't have to have a personal cert installed. But I'll add another comment to the code to point that out even more strongly.

**Comment by ibmmqmet** [comment]
Added a comment about certlabel in that sample

**Comment by QiluXie** [comment]
@ibmmqmet Oh I got it now. Thanks a lot for the explanation. That makes sense. Appreciate your help.

**Comment by SonalKhule** [comment]
@ibmmqmet I am trying to connect IBM MQ using SSL but getting SSL_INITIALISATION_ERROR.I am using .kdb certificate format.
And using reference as sample amqsconntls.js for code.

Can you please suggest me what will be reason for this error.

**Comment by SonalKhule** [comment]
Anyone has any update on above comment

**Comment by akhiilkasare** [comment]
> Anyone has any update on above comment

Did you find the solution because I am also facing the same issue

**Comment by wilkovanderveen** [comment]
I also face the same issue.

**Comment by hle24** [comment]
The error log file on my Linux system is here:  /var/mqm/errors/AMQERR01.LOG

**Comment by axp972** [comment]
> Thanks a lot @ibmmqmet . Two follow-up question:
> 
> 1. I couldn't find AMQERR01.LOG on client side. Is there any specific way to enable this client-side logging? (I did find these log files on Server side though)
> 2. In our previous testing, without SSL implementation, server side was able to see contact from client side (though it also gave the same SSL Init error 2393). But with SSL implementation, server side was not able to see any contact from client side. What would be the most probable cause in this case? Is it implying that something is wrong in the .kdb database files?
>    I will have another working session with middleware team to check if the request reaches server or not. Will keep you posted.
>    Thanks!!!

I was able to find this log file on my client machine (windows) under path-  **C:\ProgramData\IBM\MQ\errors**
