### ISSUE TITLE
Dynamic buffer size allocation

### ISSUE THREAD

**Issue by rohitjain31** [ibm-messaging/mq-mqi-nodejs#63]
Hi,

I am using ibmmq 0.9.2 and trying getSync operation.
I used var buf = Buffer.alloc(1024);
is there any way to declare buffer allocation dynamically because for me message length more.

**Comment by ibmmqmet** [comment]
You can obviously change the buffer size in your program to match the size of message you expect.
Alternatively, getting a message that is too large for the buffer will return an error - MQRC_TRUNCATED_MESSAGE_FAILED. And then you can retry with a larger buffer.

See the function pollHObj in mqi.js for an example of how that's done for the async delivery of messages.
