### ISSUE TITLE
postinstall.js fails while running behind proxy

### ISSUE THREAD

**Issue by ashfaq-shaik** [ibm-messaging/mq-mqi-nodejs#65]
When running `npm install --save ibmmq` on a machine thats behind a proxy, its not able to download c client libraries.

This is a known behaviour because node's http module doesnt support http_proxy and https_proxy environment variables. [#8381](https://github.com/nodejs/node/issues/8381)

As this doesn't use a module like `request`. How can I get this to work on a system that's behind proxy. 

If possible can you provide manual steps on how to install the c libraries on linux, once i have the tar.gz downloaded via wget.

**Comment by ibmmqmet** [comment]
See the Installation section of the README in this repository for how to install without trying to download the MQ client automatically.

Get the MQ client libraries unpacked into a local directory and then make sure the LD_LIBRARY_PATH env var points to the libs (or let the setmqenv command that's in that package do it for you).
