### ISSUE TITLE
How to uninstall mq-mqi-nodejs

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#7]
Hi
I would like to uninstall mq-mqi-nodejs and then try to install it once again. What is the procedure to uninstall mq-mqi-nodejs?
Thanks
Morten

**Comment by fjbsaper** [comment]
did you try 
npm uninstall [-g] ibmmq

**Comment by mortenLom** [comment]
No, I didn't try. will try. Thanks :-)
Morten
