### ISSUE TITLE
Error when running samples against z/OS target

### ISSUE THREAD

**Issue by rweland-volvo** [ibm-messaging/mq-mqi-nodejs#70]
Version affected: 0.9.8

The snippets in the samples that sets the ApplName 
```
if (MQC.MQCNO_CURRENT_VERSION >= 7) {
     cno.ApplName = "Node.js 9.1.2 ApplName";
}
```
will fail if run against a z/OS MQ producing the error 
> MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CNO_ERROR [2139]

See footnote here for more info.
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q095545_.htm

Ideal change would be to detect the OS version before setting this setting in the payload. I however could not find any documentation on how this is exposed in this library. I do know the information is available however, due to the MQ Exporer app being able to detect it.

**Comment by ibmmqmet** [comment]
How are you connecting to the z/OS queue manager? What version is it? I can connect as a client to a V9.1 z/OS qmgr, while setting that field.

**Comment by rweland-volvo** [comment]
I am connecting to the queue manager using the library via the host(port) method. I have confirmed it is a local queue

I have very limited access to the backend MQ information, so I can only provide what the libary and MQ Explorer report. The library reports 7 as the version from the line referenced, however when looking in MQ Explorer the version the queue reports is 08000008, as well it is reporting that the host platform is windows. Perhaps it is not an issue local to z/OS, and instead something else?
