### ISSUE TITLE
Secure Connection - KeyRepository

### ISSUE THREAD

**Issue by ChimiDEV** [ibm-messaging/mq-mqi-nodejs#71]
Hello,

Me and my Team are currently using this ibmmq npm module, but we do face some issues connecting to an IBM MQ with SSL and I'm not sure where the problem is. Would be really helpful if anyone could answer us.

First, if I understand correctly I'll have to use an KeyRepository, since the error we receive is\
`MQRC_KEY_REPOSITORY_ERROR [2381]` 

We have used certificates and `keytool`  (also the `gskit8`) to create a "TrustStore".. The created file is referenced as `sco.KeyRepository = './trustStore'`, relativs paths are okay I assume?
We set the correct `SSLCipherSpec` and declare `SSLClientAuth` as OPTIONAL.

Our `ConnectionName` is a domain with the port in parentheses and also `ChannelName` is set.
So I would assume, that everything is fine, but if I run mq.Connx(...) it still wouldn't work and we get the error defined above.

Do I miss something or how do I have to create the KeyRepository? Maybe I do not follow the guides correctly..
Our code to run mainly follows the `amqsconntls.js` example.

Thanks in advance!

**Comment by ibmmqmet** [comment]
1. The keystore must be in kdb format, along with a stashed password. See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.sec.doc/q012680_.htm
2. The keystore must contain sufficient certificates to validate the queue manager's certificate - usually the CA cert associated with the creation of the qmgr's cert.
3. You may also need to have a private cert for the user, with a suitable label. That depends on the SSLCAUTH (SSLClientAuth) attribute on the channel. And of course the qmgr would also need the signing keys in its keystore to validate the client's cert.
4. The error logs for the client and/or qmgr will usually have much more information about problems once you get beyond the step of not even finding the keystore.

**Comment by Fossil01** [comment]
Hijacking this. I need to add/replace a certificate I got from the company running the queue we dump messages on using this JS package.

The guy who did this last time is no longer working here and there is no documentation :-) I see there is a .kdb file but I can't find out how to read/dump this and how I can add a new cert to it.

Any pointers?

**Comment by chughts** [comment]
@Fossil01 you should use StackOverflow to search for or ask this question. 

eg. 
https://stackoverflow.com/questions/12893995/how-to-check-certificate-name-and-alias-in-keystore-files

Options available are `runmqakm` or `keytool`, both have options to `-list` existing certificates and to `add` new certificates.

**Comment by Fossil01** [comment]
Ah thanks. I have been looking all over on how to get `runmqakm` but keytool works too? Great, will try that. Thanks.
