### ISSUE TITLE
Performance of Get() for 10k Messages

### ISSUE THREAD

**Issue by rohitjain31** [ibm-messaging/mq-mqi-nodejs#72]
Hi,

I am trying to implement Browse functionality in node js app and using ibmmq v0.9.2. I am using Get() Asynchronous call to browse messages. It works perfectly if number of messages are not more than 100 or 200. But in my case number of messages can be up to 5k or 10k or even more.

What i observed:
1. It is taking a lot of time to browse all messages (~4 min for 4k messages)
2. Until the operation completes, other API calls get stuck and in turn nobody can login to the portal where we implemented this functionality.

I have set Polling time to 1.5 sec.

What my requirement is, first i need to show all the message IDs and size of message and if i click on message ID then i want to show the contents of messages.

Is there any way where i can just fetch all the message IDs instead of complete data?(Assuming more data size can lead to more time)

Or Can i browse messages in chunks like 50 or 100 in one go? (In that case i can implement pagination kind of functionality)

Please let me know your thoughts or let me know is there any other better way to take care of this kind of scenario.

**Comment by ibmmqmet** [comment]
The Get() method is modelled after the C MQI callback functions (MQCB/MQCTL etc), where the application is passed the entire message - you can't really specify a small buffer and permit truncation.
The tuning parameter maxConsecutiveGets may affect the performance, and when other processing gets a chance to run. 

Instead you might prefer to use the GetSync function with no blocking wait if you know there are messages to read, and you can set an appropriate buffer size to not read the body of the message (MQGMO_ACCEPT_TRUNCATED_MSG).  That way you are in control of how many are done at a time, and can do things like getting batches to paginate.

See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q026530_.htm for more advanced features of browsing messages.

**Comment by ibmmqmet** [comment]
answered
