### ISSUE TITLE
MQGMO_BROWSER_MSG_UNDER_CURSOR in async get

### ISSUE THREAD

**Issue by pure-zero** [ibm-messaging/mq-mqi-nodejs#76]
Hi Mark,

How would I go about using the MQGMO_BROWSER_MSG_UNDER_CURSOR option to first browse a message and then get it? And is this possible asynchronously.

I am trying to do this via setting the options performing another get within the async get but am getting MQRC_NO_MSG_AVAILABLE available error.

Kind regards,
Kartik.

**Comment by ibmmqmet** [comment]
I think this does what you're asking about: [amqsbrag.js.gz](https://github.com/ibm-messaging/mq-mqi-nodejs/files/3814575/amqsbrag.js.gz). It does a sync get from within the callback, knowing that the message is there. Trying to do an async get from within the async callback is unlikely to work as the cursor will probably have moved on by the time that secondary get is processed.

Then the important flag to use is MQGMO_MSG_UNDER_CURSOR.

**Comment by pure-zero** [comment]
Thanks, for that Mark. I think this will work in the way I wanted.
