### ISSUE TITLE
Run amqsgeta.js sync example with mq.Connx(_qMgr, cno, function (err, hConn) { does not work

### ISSUE THREAD

**Issue by jochen1234** [ibm-messaging/mq-mqi-nodejs#78]
[amqsconntls_aysnc.js.txt](https://github.com/ibm-messaging/mq-mqi-nodejs/files/4041427/amqsconntls_aysnc.js.txt)
Node.js version: v10.18.0

I tried not change your example to client instead server it does not. I reads just first message not queue and stops afterwards until timeout is passed.

**Comment by jochen1234** [comment]
Node.js  version: v10.18.0

I tried not change your example to client instead server it does not. I reads just first message not queue and stops afterwards until timeout is passed.

'use strict';

// Global variables
var _qMgr = "QM1";
var _qName = "DEV.QUEUE.1";
var _connName = "localhost(1414)";
var _channel = "FOR.ADMIN";
var _UserId = "admin";
var _Password = "";
var _ok = true;
var _waitInterval = 2;
var exitCode = 0;

// Import the MQ package
var mq = require('ibmmq');
var MQC = mq.MQC; // Want to refer to this export directly for simplicity
var StringDecoder = require('string_decoder').StringDecoder;
var decoder = new StringDecoder('utf8');

var connectionHandle;
var queueHandle;


function formatErr(err) {
    return "MQ call failed in " + err.message;
}

// Define some functions that will be used from the main flow
function getMessages() {
    var md = new mq.MQMD();
    var gmo = new mq.MQGMO();

    gmo.Options = MQC.MQGMO_NO_SYNCPOINT |
        MQC.MQGMO_WAIT |
        MQC.MQGMO_CONVERT |
        MQC.MQGMO_FAIL_IF_QUIESCING;

    gmo.WaitInterval = MQC.MQWI_UNLIMITED; // 3 seconds

    // Set up the callback handler to be invoked when there
    // are any incoming messages. As this is a sample, I'm going
    // to tune down the poll interval from default 10 seconds to 0.5s.
    mq.setTuningParameters({ getLoopPollTimeMs: 500 });
    mq.Get(queueHandle, md, gmo, getMessageCB);
     
    console.log("Finished get messages.")
}

// This function retrieves messages from the queue without waiting.
function getMessageCB(err, hObj, gmo, md, buf, hConn) {
    if (err) {
        if (err.mqrc == MQC.MQRC_NO_MSG_AVAILABLE) {
            console.log("no more messages");   
        } else {
            console.log(formatErr(err));
            exitCode = 1;
        }

        _ok = false;
        // We don't need any more messages delivered, so cause the
        // callback to be deleted after this one has completed.
        mq.GetDone(hObj);
    } else {
        if (md.Format=="MQSTR") {
            console.log("message <%s>", decoder.write(buf));
          } else {
            console.log("binary message: " + buf);
        }
    }
}

// When we're done, close queues and connections
function cleanup(hConn, hObj) {
    mq.Close(hObj, 0, function (err) {
        if (err) {
            console.log(formatErr(err));
        } else {
            console.log("MQCLOSE successful");
        }
        mq.Disc(hConn, function (err) {
            if (err) {
                console.log(formatErr(err));
            } else {
                console.log("MQDISC successful");
            }
        });
    });
}

// The program starts here.
// Connect to the queue manager.
console.log("Sample AMQSCONNTLS.JS start");

// Create default MQCNO and MQSCO structures
var cno = new mq.MQCNO();

// Add authentication via the MQCSP structure
var csp = new mq.MQCSP();
csp.UserId = _UserId;
csp.Password = _Password;
// Make the MQCNO refer to the MQCSP so it knows to use the structure
cno.SecurityParms = csp;

// And use the MQCD to programatically connect as a client
// First force the client mode
cno.Options |= MQC.MQCNO_CLIENT_BINDING;

// And then fill in relevant fields for the MQCD
var cd = new mq.MQCD();
cd.ConnectionName = _connName;
cd.ChannelName = _channel;
cd.SSLClientAuth = MQC.MQSCA_OPTIONAL;

// Make the MQCNO refer to the MQCD
cno.ClientConn = cd;

console.log("Trying to connect to %s at %s", _qMgr, _connName);

mq.setTuningParameters({syncMQICompat:true});

// Now we can try to connects
mq.Connx(_qMgr, cno, function (err, hConn) {
    if (err) {
        console.log(formatErr(err));

        ok = false;
    } else {
        console.log("MQCONN to %s successful ", _qMgr);
        connectionHandle = hConn;

        // Define what we want to open, and how we want to open it.
        var od = new mq.MQOD();
        od.ObjectName = _qName;
        od.ObjectType = MQC.MQOT_Q;
        var openOptions = MQC.MQOO_INPUT_AS_Q_DEF;

        mq.Open(hConn, od, openOptions, function (err, hObj) {
            queueHandle = hObj;

            if (err) {
                console.log(formatErr(err));
            } else {
                console.log("MQOPEN of %s successful", _qName);
                // And loop getting messages until done.
                getMessages();
            }
        });
    }
});

setInterval(function() {
    //if (!_ok) {
       console.log("Exiting ...");
       cleanup(connectionHandle,queueHandle);
       process.exit(exitCode);
    //}
  }, (_waitInterval + 4 ) * 1000);

**Comment by ibmmqmet** [comment]
You lost the line ` gmo.MatchOptions = MQC.MQMO_NONE` so after the first message it is looking for another message with the same msgid/correlid
