### ISSUE TITLE
Error while trying to connect an SSL channel

### ISSUE THREAD

**Issue by Tarehh** [ibm-messaging/mq-mqi-nodejs#79]
mq-mqi-nodejs LASTEST

Hi,

Im working with a provider that exposes an IBM MQ Queue that im trying to connect.
I successfully connect to an channel without SSL security. But when i try to connect to the same channel with SSL i've got this message:

CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]

One thing curious is when i remove the cd.SSLCipherSpec = "TLS_RSA_WITH_AES_256_CBC_SHA256" 
i get "CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]" error

Here is my code:

```
var QMgr = "SERVERCLI";

//Structures
var cd = new mq.MQCD();
var cno = new mq.MQCNO();
var sco = new mq.MQSCO();


cno.Options |= MQC.MQCNO_CLIENT_BINDING;

cd.ConnectionName = "XXX.XXX.XXX.XXX(33342)";
cd.ChannelName = "SSL.XXXX.SVRCONN";

cd.SSLCipherSpec = "TLS_RSA_WITH_AES_256_CBC_SHA256";
cd.SSLClientAuth = MQC.MQSCA_OPTIONAL;
sco.KeyRepository = "./key";
//cno.ApplName = "Tarjeta Cencosud Argentina";

cno.ClientConn = cd;
cno.SSLConfig = sco;


mq.Connx(QMgr, cno, function(err, conn) {
    if (err) {
        console.log(err);
    } else {
        console.log("MQCONN to %s successful ", QMgr);
        mq.Disc(conn, function(err) {
            if (err) {
                console.log(err);
            } else {
                console.log("MQDISC successful");
            }
        });
    }
});
```

**Comment by ibmmqmet** [comment]
The error logs at both the client and qmgr ends will normally have much more information on the reason for a TLS failure. But you say you're trying to connect to the "same" channel - that SVRCONN will be configured either for TLS or not; it can't do both. So does the CipherSpec in this program match what's configured on the SVRCONN?

**Comment by Tarehh** [comment]
Sorry i missed saying that the provider has two channels one without TLS (XXXX.SVRCONN) and one with TLS (SSL.XXXX.SVRCONN)
In both cases i succesfully connected with the IBM MQ Explorer and i put the same configuration that the code i attached.

I attached the image of the IBM MQ Explorer configuration of the SVRCONN with TLS.

![image](https://user-images.githubusercontent.com/3843288/72344868-18b75200-36b1-11ea-842f-8808077360e1.png)

**Comment by ibmmqmet** [comment]
Once again, what's in the error logs at both ends

**Comment by Tarehh** [comment]
do you mean this error ??:

> MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]
>     at C:\Users\ATarehZ\Desktop\MQ\fdconn\node_modules\ibmmq\lib\mqi.js:768:17
>     at Object.<anonymous> (C:\Users\ATarehZ\Desktop\MQ\fdconn\node_modules\ffi-napi\lib\_foreign_function.js:115:9) {
>   name: 'MQError',
>   message: 'CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]',
>   mqcc: 2,
>   mqccstr: 'MQCC_FAILED',
>   mqrc: 2539,
>   mqrcstr: 'MQRC_CHANNEL_CONFIG_ERROR',
>   version: '0.9.11',
>   verb: 'CONNX'
> }

**Comment by ibmmqmet** [comment]
No. The error logs - AMQERR*.LOG on both the client and server ends. At least one of those should have a fuller description of the error.

**Comment by Tarehh** [comment]
In both sides (server and client) we dont have any log for this connection attemp

**Comment by Tarehh** [comment]
Finally i made it!!. 

i just reinstalled the IBM MQ Explorer and IBM MQ on the server and then, for some reason, when i try to connect to the manager with TLS, it succesfully connected !!
