### ISSUE TITLE
Running the sample

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#8]
Hi
In the readme file it says, before running the sample:
. setmqenv -m <qmgr> -k     # to make sure MQ libraries can be found
Do I understand correctly that this command is only relevant if the MQ server is running on the same machine as the MQ client? 
In my case, the MQ server is running on a different machine. I suppose this command is not relevant for me? Am I right?
Morten

**Comment by ibmmqmet** [comment]
Read what the setmqenv command does: https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.ref.adm.doc/q083560_.htm 

It is not just for server installations.
