### ISSUE TITLE
Warning/Error when building the included docker file

### ISSUE THREAD

**Issue by a-sharma11** [ibm-messaging/mq-mqi-nodejs#80]
When i am building the sample dockerfile https://github.com/ibm-messaging/mq-mqi-nodejs/blob/master/samples/Dockerfile i am seeing this error. Is this ok to ignore?
```
../deps/libffi/src/x86/ffi64.c: In function 'classify_argument':
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
    FFI_ASSERT (0);
```

![Screen Shot 2020-01-16 at 10 29 56 AM](https://user-images.githubusercontent.com/15217582/72538056-2bfe2500-384b-11ea-8c95-5273051daad3.png)

**Comment by ibmmqmet** [comment]
This is really something that should be dealt with by the https://github.com/node-ffi-napi/node-ffi-napi project, but the message can be ignored.

**Comment by a-sharma11** [comment]
Ty!
