### ISSUE TITLE
Response queue manager functionality

### ISSUE THREAD

**Issue by Diptayan1995** [ibm-messaging/mq-mqi-nodejs#81]
While I was implementing the put functionality, I did not find any relevant example to mention the queue manager to get the response of a put request. I was able put a message  in queue, but I was not able to fetch any response of the put request. Similar functionality can be found with JMS that uses these two attrributes - ReplyToQ, ReplyToQMgr. Can anyone give me any lead so that Ican implement this functionality?

mq-mqi-nodejs version : 0.9.11

**Comment by ibmmqmet** [comment]
This library is based on the procedural MQI. So you can follow all the product-provided documentation and samples for C programs. 

In this case you need to set the ReplyToQ/ReplyToQMgr in the MQMD. See for example https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q023100_.htm and https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q097410_.htm
