### ISSUE TITLE
How handle disconnect?

### ISSUE THREAD

**Issue by calmeyda** [ibm-messaging/mq-mqi-nodejs#82]
Hi I keep connections and queues open, but how may I handle on disconnect? I get an error "parameter of type mqobject must be provided", exists any event so I can detect a disconnect?

**Comment by ibmmqmet** [comment]
I don't really understand your question. You should be passing the hConn object returned from Conn() to the Disc() verb when you want to disconnect.

**Comment by calmeyda** [comment]
How handle if MQ server (not my app) close my connection? An event is fired? or Can I check a property on connection instance to check if still valid?

**Comment by ibmmqmet** [comment]
If the connection is broken (queue manager ends, network fails etc) then the next time an MQI verb is called you will get an error. Probably 2009 (MQRC_CONNECTION_BROKEN). There's no asynchronous notification of the failure, except that if you've got an active Get() callback function waiting for messages then it will be given the 2009 error.

**Comment by calmeyda** [comment]
Thanks! I will handle of that way
