### ISSUE TITLE
MQ error

### ISSUE THREAD

**Issue by svanka2005** [ibm-messaging/mq-mqi-nodejs#86]
I did set LD_LIBRARY_PATH env variable to point to ibmmq/lib folder. Still getting below error. 

Appreciate your help on this.

Cannot find MQ C library.
  Has the C client been installed?
  Have you run setmqenv?
2020-05-26 13:47:25:330 error : Error: Dynamic Linking Error: Win32 error 126

**Comment by ibmmqmet** [comment]
LD_LIBRARY_PATH is a Unix env var but your error suggests you are using Windows. And have you done the various suggestions such as running setmqenv? What was the result?

**Comment by svanka2005** [comment]
Thank you for your reply. I passed through that error. I did ran setmqenv.

Right now, my nodejs app is not able to connect to remeote queue (2059).

Maybe issue with authentication.

**Comment by svanka2005** [comment]
Thank you for your reply. I passed through that error. I did ran setmqenv.

Right now, my nodejs app is not able to connect to remote queue (2059).

Maybe issue with authentication.

**Comment by ibmmqmet** [comment]
No recent update - closing
