### ISSUE TITLE
Mac OS X (readme and a bug)

### ISSUE THREAD

**Issue by Strnadj** [ibm-messaging/mq-mqi-nodejs#87]
I am missing a bit a MacOS X guide how to make this thing work :-) 

```
1. download C MQ client from https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/mactoolkit/
2. unzip that in some meaningful directory could be /Users/strnadj/Libs/ibm-mq
3. add export PATH=/Users/strnadj/Libs/ibm-mq/bin:/Users/strnadj/Libs/ibm-mq/samp/bin:$PATH to your .zshrc / .bashrc profile
4. There is "NO" setmqenv command in C MQ client build, also MQ Explorer does not work - only Linux and Windows platforms are supported and MQ Console is limited, you have to configure it via command line.
5. run npm i ibmmq
6. you have to start your application with LD_LIBRARY_PATH=/Users/strnadj/Libs/ibm-mq/lib64/ npm run start or export LD_LIBRARY_PATH in your zshrc / bashrc profile files. Otherwise you will facing error:
Error: Dynamic Linking Error: dlopen(/opt/mqm/lib/libmqm_r.dylib, 2): image not found
```

**Comment by ibmmqmet** [comment]
mq.Connx(qMgr, cno, function(err,conn)

but you then have

mq.Open(hConn,od,openOptions,function(err,hObj)

**Comment by Strnadj** [comment]
@ibmmqmet thx, it works. But it's really weird for me too. If I try:

```
~/Projects/to_remove/test_ibmmq ❯ cat test.js                                                                                                                                                                                                                                                                                                             L 18.77 RAM 4.96G
console.log(d);
~/Projects/to_remove/test_ibmmq ❯ node test.js                                                                                                                                                                                                                                                                                                            L 18.54 RAM 4.47G
/Users/strnadj/Projects/to_remove/test_ibmmq/test.js:1
console.log(d);
            ^

ReferenceError: d is not defined
    at Object.<anonymous> (/Users/strnadj/Projects/to_remove/test_ibmmq/test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```
it works as expected... but on the other side, you can't be sure that *hConn* or *conn* property is properly set up. This kind of errors:

```
~/Projects/to_remove/test_ibmmq ❯ node client.js                                                                                                                                                                                                                                                                                                           L 3.56 RAM 4.22G
Sample AMQSCONN.JS start
MQCONN to test successful
libc++abi.dylib: terminating with uncaught exception of type Napi::Error: Parameter of type MQQueueManager must be provided
[1]    89523 abort      node client.js
```
kills the whole process instead of just throwing an exception which could be caught...

**Comment by ibmmqmet** [comment]
An TypeError exception is being thrown when the hConn is not correctly setup ("Parameter of type ... must be provided" - likely being passed in as null) but it seems to then be being caught by the FFI/NAPI code rather than percolating back to the user level (various things happening on 2ary callback threads perhaps when the MQ calls are being made asynchronously), and then it's rethrown as a C++ exception. I don't know how that can be caught and searching suggests that there may be some known problems with the napi interface reporting some things as uncaught even when they shouldn't be.

**Comment by creasman** [comment]
Was there a resolution for this?  I'm seeing the same error on Mac.  It was working for me once but stopped at some point over the past couple of weeks (not sure when or why).  I hit the problem the first time and resolved it by soft linking the MQ client binaries into the path.  This no longer appears to work.  As I was creating a new Node project that includes this IBM MQ Node package, I'm again seeing the same error as reported in the opening post, only it's failing on the import statement for me:
```
    Dynamic Linking Error: dlopen(/Users/ap677/Projects/identity-consent-proc/app/node_modules/ibmmq/redist/lib64/libmqm_r.dylib, 2): image not found

      4 | import { Injectable, Logger } from '@nestjs/common';
      5 | import * as config from 'config';
    > 6 | import * as mq from 'ibmmq';
        | ^
```
I followed the same steps (1-6) as outlined above.  The dspmqver command gives this information:
```
Name:        IBM MQ
Version:     9.1.5.0
Level:       p915-L200318.DE
BuildType:   IKAP - (Production)
Platform:    IBM MQ for macOS
Mode:        64-bit
O/S:         Darwin 18.7.0
InstName:    MQNI91L20031800D
InstDesc:    IBM MQ V9.1.5.0 (Unzipped)
Primary:     N/A
InstPath:    /opt/mqm
DataPath:    /Users/ap677/IBM/MQ/data
MaxCmdLevel: 915
```
Along these lines could we get a version of this Node package that installs directly onto the Mac, just like the other Linux flavors?  From what I can tell the postinstall.js has code for this path that is commented out.

**Comment by prabhatmishra33** [comment]
facing the same issues as described above, @creasman did you managed to resolve it ?

**Comment by creasman** [comment]
@prabhatmishra33 Yes, after some effort this are the steps that worked for me:

1. Download and unpack the IBM MQ MacOS client bundle in /opt/mqm.
2. Update the path to include /opt/mqm/bin and /opt/mqm/samp/bin (not needed for ibmmq package, but required if you want to run MQ client commands from command line).
3. Run `ln -sf /opt/mqm/lib64/* /usr/local/lib/`.
4. Run `install_name_tool -change @rpath/libmqe_r.dylib /opt/mqm/lib64/libmqe_r.dylib /opt/mqm/lib64/libmqm_r.dylib` to localize the library.
5. Run `otool -L /opt/mqm/lib64/libmqm_r.dylib` to verify the localization.
6. Set `MQIJS_NOREDIST=1` in my local .npmrc file to let ibmmq package know I have already installed the MQ client.
7. Run `npm install` as usual.

I’m not sure what the right resolution is for this.  The NodeJS MQ client surfaces the problem, but seems the fix might lie in the MacOS MQ Toolkit (even though it does not seem to have any issues when you run a native command such as dspmqver).

**Comment by prabhatmishra33** [comment]
@creasman Thanks a lot. from your above steps step 4 didn't worked,

error:error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't map file: /usr/local/lib/ (Invalid argument)

but i moved to next command and it worked.

**Comment by creasman** [comment]
Hmm.... that's interesting as step 4 is what does the "magic" of localizing the library image.  It could be that step 3 was sufficient.  I did not always have to run step 4.  This was added after the simpler procedure stopped working for me.

**Comment by parzhitsky** [comment]
@creasman Thanks, these steps helped me to fix this issue. @prabhatmishra33 I had to run the 4th step with `sudo`

**Comment by prabhatmishra33** [comment]
@creasman could you please tell me, what did you get the output by this cmd `otool -L /opt/mqm/lib64/libmqm_r.dylib`.
Actually, I am facing a strange issue which is described in above #112 that's why I want to verify the installation.

**Comment by creasman** [comment]
This is what the command returns for me (same as yours):
```
	@rpath/libmqm_r.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/mqm/lib64/libmqe_r.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```
