### ISSUE TITLE
CF push is failing for ibmmq for permission issues

### ISSUE THREAD

**Issue by nidhiag** [ibm-messaging/mq-mqi-nodejs#91]
ibmmq version : 0.9.14
Error Coming while doing CF PUSH of application consuming `ibmmq`
Uploading 237.7M, 56347 files
Done uploading               
FAILED
Error processing app files: Error uploading application.
The resource file mode is invalid: File mode '0444' with path 'temp/loopback-connector-ibmmq/node_modules/ibmmq/redist/lap/licenses/LA_lt' is invalid. Minimum file mode is '0600'

The resource file mode is invalid: File mode '0444' with path 'temp/loopback-connector-ibmmq/node_modules/ibmmq/redist/lib/iconv/0342039E.tbl' is invalid. Minimum file mode is '0600'

I have added permission to all the files 
`sudo chmod 0600 -R redist/*`

FAILED
Error processing app files: Error processing app files in '/home/nidhi/loopback-connector-provider': lstat /home/nidhi/loopback-connector-provider/node_modules/ibmmq/redist/bin/runmqsc: permission denied

**Comment by nidhiag** [comment]
The resource file mode is invalid: File mode '0555' with path 'node_modules/ibmmq/redist/gskit8/bin/gsk8capicmd' is invalid. Minimum file mode is '0600'

**Comment by ibmmqmet** [comment]
This sounds like something you should take up with whatever is providing the `CF PUSH` command. There is no MQ reason for those files to change permissions. Making program files writable is inherently a security risk. And changing them blindly as you have done can stop things working as you have removed the executable bits.

If the minimum file permissions that tool requires is 0600, then doing something like
`find ibmmq/redist | xargs chmod u+rw` might be sufficient. But it's not something we would recommend or make any changes for in the MQ packages.

**Comment by ibmmqmet** [comment]
Not a problem with this repo
