### ISSUE TITLE
terminate called after throwing an instance of 'Napi::Error'

### ISSUE THREAD

**Issue by strat1971** [ibm-messaging/mq-mqi-nodejs#99]
I am using mq-,qi-nodejs 0.9.15.

When my application is ended using a SIGTERM, we get this error: 
`terminate called after throwing an instance of 'Napi::Error'.`

Background:
-
When the application starts, it connects to the queue manager using Connx, then opens the queue using Open.
The open options are set like this:

`let openOptions = mqc.MQOO_INPUT_AS_Q_DEF | mqc.MQOO_BROWSE; // Indicate non-destructive retrieval needed`

The callback passed in with the Open sets up the listeners for SIGTERM and SIGINT. These listeners call a cleanup function that does a Close call followed by a Disc call. 

Then the application does a Get call. The get message options are set like this:

```
const gmo = this.ibmMqConnector.createMQGMO(); // Get-message options (MQGMO)
gmo.Options =
      this.ibmMqConnector.getMQC().MQGMO_NO_SYNCPOINT | // Get a message without syncpoint control.
      this.ibmMqConnector.getMQC().MQGMO_WAIT | // Wait for the message to arrive
      this.ibmMqConnector.getMQC().MQGMO_CONVERT | // Seems to convert between char sets
      this.ibmMqConnector.getMQC().MQGMO_FAIL_IF_QUIESCING | // Force the MQGET call to fail if the queue manager is in the quiescing state.
      this.ibmMqConnector.getMQC().MQGMO_BROWSE_FIRST; // To start with, set the option to browse the FIRST message on the queue
    gmo.MatchOptions = this.ibmMqConnector.getMQC().MQMO_NONE; // Do not use matches in selecting the message to be returned.
    gmo.WaitInterval = this.ibmMqConnector.getMQC().MQWI_UNLIMITED; // Wait forever until a message arrives

```
(Note the ibmMqConnector is a wrapper for the ibmmq package.)

The tuning parameters are:
`this.ibmMqConnector.setTuningParameters({ getLoopPollTimeMs: 10000 });`

A  receive message callback passed in with the Get the reads messages and calls the downstream process.

Observations:
-
I can see that the  receive message callback is being called after we get the terminate called after throwing an instance of 'Napi::Error' message. The first thing that callback tries to do is to read the message descriptor, which is null or undefined at this point.

By now the Open callback has processed the SIGTERM and the Close and the Disc have completed successfully.

I have tried adding a call to GetDone in the cleanup function, which gets the user context and then deletes it.
I tried removing the MQGMO_FAIL_IF_QUIESCING option.

Question:
-
Is there a way to avoid this error on termination, either by improving the cleanup or by setting up the application differently?

**Comment by ibmmqmet** [comment]
I'm not really certain what your program flow is, and therfore where the exception is coming from. I did take the amqsget sample and made a few mods to it to catch signals, and found a flow through GetDone that would always throw the napi exception if the hconn/hobj had been closed, instead of invoking a callback. Putting a try/catch around the GetDone dealt with that (though I will improve the base code at some point.)

**Comment by ibmmqmet** [comment]
update went into 0.9.15 that should avoid error

**Comment by strat1971** [comment]
Thanks Mark.


Jim
